# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/background.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gui import solidfill_pb2 as gui_dot_solidfill__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/background.proto',
  package='gui.background',
  syntax='proto2',
  serialized_pb=_b('\n\x14gui/background.proto\x12\x0egui.background\x1a\x13gui/solidfill.proto\"d\n\nBackground\x12.\n\nsolid_fill\x18\x01 \x01(\x0e\x32\x18.gui.solidfill.SolidFillH\x00\x12\x18\n\x0esolid_fill_rgb\x18\x02 \x01(\rH\x00\x42\x0c\n\nbackground')
  ,
  dependencies=[gui_dot_solidfill__pb2.DESCRIPTOR,])




_BACKGROUND = _descriptor.Descriptor(
  name='Background',
  full_name='gui.background.Background',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solid_fill', full_name='gui.background.Background.solid_fill', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='solid_fill_rgb', full_name='gui.background.Background.solid_fill_rgb', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='background', full_name='gui.background.Background.background',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=61,
  serialized_end=161,
)

_BACKGROUND.fields_by_name['solid_fill'].enum_type = gui_dot_solidfill__pb2._SOLIDFILL
_BACKGROUND.oneofs_by_name['background'].fields.append(
  _BACKGROUND.fields_by_name['solid_fill'])
_BACKGROUND.fields_by_name['solid_fill'].containing_oneof = _BACKGROUND.oneofs_by_name['background']
_BACKGROUND.oneofs_by_name['background'].fields.append(
  _BACKGROUND.fields_by_name['solid_fill_rgb'])
_BACKGROUND.fields_by_name['solid_fill_rgb'].containing_oneof = _BACKGROUND.oneofs_by_name['background']
DESCRIPTOR.message_types_by_name['Background'] = _BACKGROUND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Background = _reflection.GeneratedProtocolMessageType('Background', (_message.Message,), dict(
  DESCRIPTOR = _BACKGROUND,
  __module__ = 'gui.background_pb2'
  # @@protoc_insertion_point(class_scope:gui.background.Background)
  ))
_sym_db.RegisterMessage(Background)


# @@protoc_insertion_point(module_scope)
