# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/border.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gui import background_pb2 as gui_dot_background__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/border.proto',
  package='gui.border',
  syntax='proto2',
  serialized_pb=_b('\n\x10gui/border.proto\x12\ngui.border\x1a\x14gui/background.proto\"j\n\x06\x42order\x12&\n\x05style\x18\x01 \x02(\x0e\x32\x17.gui.border.BorderStyle\x12)\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x1a.gui.background.Background\x12\r\n\x05width\x18\x03 \x01(\r*D\n\x0b\x42orderStyle\x12\x10\n\x0cSOLID_BORDER\x10\x00\x12\x11\n\rOUTSET_BORDER\x10\x01\x12\x10\n\x0cINSET_BORDER\x10\x02')
  ,
  dependencies=[gui_dot_background__pb2.DESCRIPTOR,])

_BORDERSTYLE = _descriptor.EnumDescriptor(
  name='BorderStyle',
  full_name='gui.border.BorderStyle',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOLID_BORDER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTSET_BORDER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSET_BORDER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=162,
  serialized_end=230,
)
_sym_db.RegisterEnumDescriptor(_BORDERSTYLE)

BorderStyle = enum_type_wrapper.EnumTypeWrapper(_BORDERSTYLE)
SOLID_BORDER = 0
OUTSET_BORDER = 1
INSET_BORDER = 2



_BORDER = _descriptor.Descriptor(
  name='Border',
  full_name='gui.border.Border',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='style', full_name='gui.border.Border.style', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='gui.border.Border.color', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='gui.border.Border.width', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=160,
)

_BORDER.fields_by_name['style'].enum_type = _BORDERSTYLE
_BORDER.fields_by_name['color'].message_type = gui_dot_background__pb2._BACKGROUND
DESCRIPTOR.message_types_by_name['Border'] = _BORDER
DESCRIPTOR.enum_types_by_name['BorderStyle'] = _BORDERSTYLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Border = _reflection.GeneratedProtocolMessageType('Border', (_message.Message,), dict(
  DESCRIPTOR = _BORDER,
  __module__ = 'gui.border_pb2'
  # @@protoc_insertion_point(class_scope:gui.border.Border)
  ))
_sym_db.RegisterMessage(Border)


# @@protoc_insertion_point(module_scope)
