# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/draw_bitmap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/draw_bitmap.proto',
  package='gui.draw_bitmap',
  syntax='proto2',
  serialized_pb=_b('\n\x15gui/draw_bitmap.proto\x12\x0fgui.draw_bitmap\"?\n\nDrawBitmap\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12#\n\x04\x61rea\x18\x02 \x01(\x0b\x32\x15.gui.draw_bitmap.Area\";\n\x04\x41rea\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\r\n\x05width\x18\x03 \x02(\r\x12\x0e\n\x06height\x18\x04 \x02(\r')
)




_DRAWBITMAP = _descriptor.Descriptor(
  name='DrawBitmap',
  full_name='gui.draw_bitmap.DrawBitmap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='gui.draw_bitmap.DrawBitmap.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area', full_name='gui.draw_bitmap.DrawBitmap.area', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=105,
)


_AREA = _descriptor.Descriptor(
  name='Area',
  full_name='gui.draw_bitmap.Area',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='gui.draw_bitmap.Area.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='gui.draw_bitmap.Area.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='gui.draw_bitmap.Area.width', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='gui.draw_bitmap.Area.height', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=166,
)

_DRAWBITMAP.fields_by_name['area'].message_type = _AREA
DESCRIPTOR.message_types_by_name['DrawBitmap'] = _DRAWBITMAP
DESCRIPTOR.message_types_by_name['Area'] = _AREA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrawBitmap = _reflection.GeneratedProtocolMessageType('DrawBitmap', (_message.Message,), dict(
  DESCRIPTOR = _DRAWBITMAP,
  __module__ = 'gui.draw_bitmap_pb2'
  # @@protoc_insertion_point(class_scope:gui.draw_bitmap.DrawBitmap)
  ))
_sym_db.RegisterMessage(DrawBitmap)

Area = _reflection.GeneratedProtocolMessageType('Area', (_message.Message,), dict(
  DESCRIPTOR = _AREA,
  __module__ = 'gui.draw_bitmap_pb2'
  # @@protoc_insertion_point(class_scope:gui.draw_bitmap.Area)
  ))
_sym_db.RegisterMessage(Area)


# @@protoc_insertion_point(module_scope)
