# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/menu_dialog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/menu_dialog.proto',
  package='gui.menu_dialog',
  syntax='proto2',
  serialized_pb=_b('\n\x15gui/menu_dialog.proto\x12\x0fgui.menu_dialog\"\\\n\nMenuDialog\x12\x0f\n\x07\x63\x61ption\x18\x01 \x02(\t\x12,\n\titem_list\x18\x02 \x02(\x0b\x32\x19.gui.menu_dialog.ItemList\x12\x0f\n\x07timeout\x18\x03 \x01(\r\"0\n\x08ItemList\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.gui.menu_dialog.Item\"\x16\n\x08LeafItem\x12\n\n\x02id\x18\x01 \x02(\r\"z\n\x04Item\x12\x0c\n\x04text\x18\x01 \x02(\t\x12.\n\tleaf_item\x18\x02 \x01(\x0b\x32\x19.gui.menu_dialog.LeafItemH\x00\x12,\n\x07submenu\x18\x03 \x01(\x0b\x32\x19.gui.menu_dialog.ItemListH\x00\x42\x06\n\x04item\"\x1a\n\x0cSelectedItem\x12\n\n\x02id\x18\x01 \x02(\r')
)




_MENUDIALOG = _descriptor.Descriptor(
  name='MenuDialog',
  full_name='gui.menu_dialog.MenuDialog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caption', full_name='gui.menu_dialog.MenuDialog.caption', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_list', full_name='gui.menu_dialog.MenuDialog.item_list', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='gui.menu_dialog.MenuDialog.timeout', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=134,
)


_ITEMLIST = _descriptor.Descriptor(
  name='ItemList',
  full_name='gui.menu_dialog.ItemList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='gui.menu_dialog.ItemList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=184,
)


_LEAFITEM = _descriptor.Descriptor(
  name='LeafItem',
  full_name='gui.menu_dialog.LeafItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gui.menu_dialog.LeafItem.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=208,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='gui.menu_dialog.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='gui.menu_dialog.Item.text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leaf_item', full_name='gui.menu_dialog.Item.leaf_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='submenu', full_name='gui.menu_dialog.Item.submenu', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='item', full_name='gui.menu_dialog.Item.item',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=210,
  serialized_end=332,
)


_SELECTEDITEM = _descriptor.Descriptor(
  name='SelectedItem',
  full_name='gui.menu_dialog.SelectedItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='gui.menu_dialog.SelectedItem.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=360,
)

_MENUDIALOG.fields_by_name['item_list'].message_type = _ITEMLIST
_ITEMLIST.fields_by_name['items'].message_type = _ITEM
_ITEM.fields_by_name['leaf_item'].message_type = _LEAFITEM
_ITEM.fields_by_name['submenu'].message_type = _ITEMLIST
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['leaf_item'])
_ITEM.fields_by_name['leaf_item'].containing_oneof = _ITEM.oneofs_by_name['item']
_ITEM.oneofs_by_name['item'].fields.append(
  _ITEM.fields_by_name['submenu'])
_ITEM.fields_by_name['submenu'].containing_oneof = _ITEM.oneofs_by_name['item']
DESCRIPTOR.message_types_by_name['MenuDialog'] = _MENUDIALOG
DESCRIPTOR.message_types_by_name['ItemList'] = _ITEMLIST
DESCRIPTOR.message_types_by_name['LeafItem'] = _LEAFITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['SelectedItem'] = _SELECTEDITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MenuDialog = _reflection.GeneratedProtocolMessageType('MenuDialog', (_message.Message,), dict(
  DESCRIPTOR = _MENUDIALOG,
  __module__ = 'gui.menu_dialog_pb2'
  # @@protoc_insertion_point(class_scope:gui.menu_dialog.MenuDialog)
  ))
_sym_db.RegisterMessage(MenuDialog)

ItemList = _reflection.GeneratedProtocolMessageType('ItemList', (_message.Message,), dict(
  DESCRIPTOR = _ITEMLIST,
  __module__ = 'gui.menu_dialog_pb2'
  # @@protoc_insertion_point(class_scope:gui.menu_dialog.ItemList)
  ))
_sym_db.RegisterMessage(ItemList)

LeafItem = _reflection.GeneratedProtocolMessageType('LeafItem', (_message.Message,), dict(
  DESCRIPTOR = _LEAFITEM,
  __module__ = 'gui.menu_dialog_pb2'
  # @@protoc_insertion_point(class_scope:gui.menu_dialog.LeafItem)
  ))
_sym_db.RegisterMessage(LeafItem)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'gui.menu_dialog_pb2'
  # @@protoc_insertion_point(class_scope:gui.menu_dialog.Item)
  ))
_sym_db.RegisterMessage(Item)

SelectedItem = _reflection.GeneratedProtocolMessageType('SelectedItem', (_message.Message,), dict(
  DESCRIPTOR = _SELECTEDITEM,
  __module__ = 'gui.menu_dialog_pb2'
  # @@protoc_insertion_point(class_scope:gui.menu_dialog.SelectedItem)
  ))
_sym_db.RegisterMessage(SelectedItem)


# @@protoc_insertion_point(module_scope)
