# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/screen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gui import background_pb2 as gui_dot_background__pb2
from gui import foreground_pb2 as gui_dot_foreground__pb2
from gui import widget_pb2 as gui_dot_widget__pb2
from gui import border_pb2 as gui_dot_border__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/screen.proto',
  package='gui.screen',
  syntax='proto2',
  serialized_pb=_b('\n\x10gui/screen.proto\x12\ngui.screen\x1a\x14gui/background.proto\x1a\x14gui/foreground.proto\x1a\x10gui/widget.proto\x1a\x10gui/border.proto\"\xb2\x01\n\nShowScreen\x12 \n\x04root\x18\x01 \x02(\x0b\x32\x12.gui.widget.Widget\x12.\n\nbackground\x18\x02 \x01(\x0b\x32\x1a.gui.background.Background\x12.\n\nforeground\x18\x03 \x01(\x0b\x32\x1a.gui.foreground.Foreground\x12\"\n\x06\x62order\x18\x04 \x01(\x0b\x32\x12.gui.border.Border')
  ,
  dependencies=[gui_dot_background__pb2.DESCRIPTOR,gui_dot_foreground__pb2.DESCRIPTOR,gui_dot_widget__pb2.DESCRIPTOR,gui_dot_border__pb2.DESCRIPTOR,])




_SHOWSCREEN = _descriptor.Descriptor(
  name='ShowScreen',
  full_name='gui.screen.ShowScreen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='root', full_name='gui.screen.ShowScreen.root', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='background', full_name='gui.screen.ShowScreen.background', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foreground', full_name='gui.screen.ShowScreen.foreground', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='border', full_name='gui.screen.ShowScreen.border', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=291,
)

_SHOWSCREEN.fields_by_name['root'].message_type = gui_dot_widget__pb2._WIDGET
_SHOWSCREEN.fields_by_name['background'].message_type = gui_dot_background__pb2._BACKGROUND
_SHOWSCREEN.fields_by_name['foreground'].message_type = gui_dot_foreground__pb2._FOREGROUND
_SHOWSCREEN.fields_by_name['border'].message_type = gui_dot_border__pb2._BORDER
DESCRIPTOR.message_types_by_name['ShowScreen'] = _SHOWSCREEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShowScreen = _reflection.GeneratedProtocolMessageType('ShowScreen', (_message.Message,), dict(
  DESCRIPTOR = _SHOWSCREEN,
  __module__ = 'gui.screen_pb2'
  # @@protoc_insertion_point(class_scope:gui.screen.ShowScreen)
  ))
_sym_db.RegisterMessage(ShowScreen)


# @@protoc_insertion_point(module_scope)
