# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/solidfill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/solidfill.proto',
  package='gui.solidfill',
  syntax='proto2',
  serialized_pb=_b('\n\x13gui/solidfill.proto\x12\rgui.solidfill*v\n\tSolidFill\x12\x14\n\x10SOLID_FILL_BLACK\x10\x00\x12\x14\n\x10SOLID_FILL_WHITE\x10\x01\x12\x12\n\x0eSOLID_FILL_RED\x10\x02\x12\x14\n\x10SOLID_FILL_GREEN\x10\x03\x12\x13\n\x0fSOLID_FILL_BLUE\x10\x04')
)

_SOLIDFILL = _descriptor.EnumDescriptor(
  name='SolidFill',
  full_name='gui.solidfill.SolidFill',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SOLID_FILL_BLACK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLID_FILL_WHITE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLID_FILL_RED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLID_FILL_GREEN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOLID_FILL_BLUE', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=38,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_SOLIDFILL)

SolidFill = enum_type_wrapper.EnumTypeWrapper(_SOLIDFILL)
SOLID_FILL_BLACK = 0
SOLID_FILL_WHITE = 1
SOLID_FILL_RED = 2
SOLID_FILL_GREEN = 3
SOLID_FILL_BLUE = 4


DESCRIPTOR.enum_types_by_name['SolidFill'] = _SOLIDFILL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
