# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui/text_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui/text_id.proto',
  package='gui.text_id',
  syntax='proto2',
  serialized_pb=_b('\n\x11gui/text_id.proto\x12\x0bgui.text_id*\x91\x01\n\x06TextId\x12\x0e\n\nIP_ADDRESS\x10\x00\x12\x19\n\x15\x45THERNET_PORT1_STATUS\x10\x01\x12\x19\n\x15\x45THERNET_PORT2_STATUS\x10\x02\x12\x14\n\x10\x46IRMWARE_VERSION\x10\x03\x12\x11\n\rSERIAL_NUMBER\x10\x04\x12\n\n\x06UPTIME\x10\x05\x12\x0c\n\x08\x44OWNTIME\x10\x06')
)

_TEXTID = _descriptor.EnumDescriptor(
  name='TextId',
  full_name='gui.text_id.TextId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IP_ADDRESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETHERNET_PORT1_STATUS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ETHERNET_PORT2_STATUS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIRMWARE_VERSION', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERIAL_NUMBER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPTIME', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNTIME', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=35,
  serialized_end=180,
)
_sym_db.RegisterEnumDescriptor(_TEXTID)

TextId = enum_type_wrapper.EnumTypeWrapper(_TEXTID)
IP_ADDRESS = 0
ETHERNET_PORT1_STATUS = 1
ETHERNET_PORT2_STATUS = 2
FIRMWARE_VERSION = 3
SERIAL_NUMBER = 4
UPTIME = 5
DOWNTIME = 6


DESCRIPTOR.enum_types_by_name['TextId'] = _TEXTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
