# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/ultralight/auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.av2 import args_pb2 as mifare_dot_av2_dot_args__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/ultralight/auth.proto',
  package='mifare.ultralight.auth',
  syntax='proto2',
  serialized_pb=_b('\n\x1cmifare/ultralight/auth.proto\x12\x16mifare.ultralight.auth\x1a\x15mifare/av2/args.proto\"\x1d\n\x08\x43learKey\x12\x11\n\tclear_key\x18\x01 \x02(\x0c\"c\n\x06SamKey\x12:\n\x08\x61v2_args\x18\x01 \x02(\x0b\x32(.mifare.av2.args.AuthenticationArguments\x12\x1d\n\x15\x64iversification_input\x18\x02 \x01(\x0c')
  ,
  dependencies=[mifare_dot_av2_dot_args__pb2.DESCRIPTOR,])




_CLEARKEY = _descriptor.Descriptor(
  name='ClearKey',
  full_name='mifare.ultralight.auth.ClearKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clear_key', full_name='mifare.ultralight.auth.ClearKey.clear_key', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=108,
)


_SAMKEY = _descriptor.Descriptor(
  name='SamKey',
  full_name='mifare.ultralight.auth.SamKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='av2_args', full_name='mifare.ultralight.auth.SamKey.av2_args', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diversification_input', full_name='mifare.ultralight.auth.SamKey.diversification_input', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=209,
)

_SAMKEY.fields_by_name['av2_args'].message_type = mifare_dot_av2_dot_args__pb2._AUTHENTICATIONARGUMENTS
DESCRIPTOR.message_types_by_name['ClearKey'] = _CLEARKEY
DESCRIPTOR.message_types_by_name['SamKey'] = _SAMKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearKey = _reflection.GeneratedProtocolMessageType('ClearKey', (_message.Message,), dict(
  DESCRIPTOR = _CLEARKEY,
  __module__ = 'mifare.ultralight.auth_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.auth.ClearKey)
  ))
_sym_db.RegisterMessage(ClearKey)

SamKey = _reflection.GeneratedProtocolMessageType('SamKey', (_message.Message,), dict(
  DESCRIPTOR = _SAMKEY,
  __module__ = 'mifare.ultralight.auth_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.auth.SamKey)
  ))
_sym_db.RegisterMessage(SamKey)


# @@protoc_insertion_point(module_scope)
