# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/ultralight/bulk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.ultralight import auth_pb2 as mifare_dot_ultralight_dot_auth__pb2
from mifare.ultralight import read_pb2 as mifare_dot_ultralight_dot_read__pb2
from mifare.ultralight import write_pb2 as mifare_dot_ultralight_dot_write__pb2
from mifare.ultralight import password_pb2 as mifare_dot_ultralight_dot_password__pb2
from mifare.ultralight.counter import get_pb2 as mifare_dot_ultralight_dot_counter_dot_get__pb2
from mifare.ultralight.counter import increment_pb2 as mifare_dot_ultralight_dot_counter_dot_increment__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/ultralight/bulk.proto',
  package='mifare.ultralight.bulk',
  syntax='proto2',
  serialized_pb=_b('\n\x1cmifare/ultralight/bulk.proto\x12\x16mifare.ultralight.bulk\x1a\x1cmifare/ultralight/auth.proto\x1a\x1cmifare/ultralight/read.proto\x1a\x1dmifare/ultralight/write.proto\x1a mifare/ultralight/password.proto\x1a#mifare/ultralight/counter/get.proto\x1a)mifare/ultralight/counter/increment.proto\"D\n\rBulkOperation\x12\x33\n\noperations\x18\x01 \x03(\x0b\x32\x1f.mifare.ultralight.bulk.Command\"D\n\nBulkResult\x12\x36\n\x07results\x18\x01 \x03(\x0b\x32%.mifare.ultralight.bulk.CommandResult\"\xa8\x04\n\x07\x43ommand\x12\x37\n\nread_pages\x18\x01 \x01(\x0b\x32!.mifare.ultralight.read.ReadPagesH\x00\x12:\n\x0bwrite_pages\x18\x02 \x01(\x0b\x32#.mifare.ultralight.write.WritePagesH\x00\x12@\n\x0bget_counter\x18\x03 \x01(\x0b\x32).mifare.ultralight.counter.get.GetCounterH\x00\x12R\n\x11increment_counter\x18\x04 \x01(\x0b\x32\x35.mifare.ultralight.counter.increment.IncrementCounterH\x00\x12=\n\x11\x61uth_on_clear_key\x18\x05 \x01(\x0b\x32 .mifare.ultralight.auth.ClearKeyH\x00\x12\x39\n\x0f\x61uth_on_sam_key\x18\x06 \x01(\x0b\x32\x1e.mifare.ultralight.auth.SamKeyH\x00\x12H\n\x13\x61uth_clear_password\x18\x07 \x01(\x0b\x32).mifare.ultralight.password.ClearPasswordH\x00\x12\x44\n\x11\x61uth_sam_password\x18\x08 \x01(\x0b\x32\'.mifare.ultralight.password.SamPasswordH\x00\x42\x08\n\x06MfrCmd\"\x92\x01\n\rCommandResult\x12.\n\x05pages\x18\x01 \x01(\x0b\x32\x1d.mifare.ultralight.read.PagesH\x00\x12\x44\n\rcounter_value\x18\x02 \x01(\x0b\x32+.mifare.ultralight.counter.get.CounterValueH\x00\x42\x0b\n\tMfrResult')
  ,
  dependencies=[mifare_dot_ultralight_dot_auth__pb2.DESCRIPTOR,mifare_dot_ultralight_dot_read__pb2.DESCRIPTOR,mifare_dot_ultralight_dot_write__pb2.DESCRIPTOR,mifare_dot_ultralight_dot_password__pb2.DESCRIPTOR,mifare_dot_ultralight_dot_counter_dot_get__pb2.DESCRIPTOR,mifare_dot_ultralight_dot_counter_dot_increment__pb2.DESCRIPTOR,])




_BULKOPERATION = _descriptor.Descriptor(
  name='BulkOperation',
  full_name='mifare.ultralight.bulk.BulkOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operations', full_name='mifare.ultralight.bulk.BulkOperation.operations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=329,
)


_BULKRESULT = _descriptor.Descriptor(
  name='BulkResult',
  full_name='mifare.ultralight.bulk.BulkResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='mifare.ultralight.bulk.BulkResult.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=399,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='mifare.ultralight.bulk.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_pages', full_name='mifare.ultralight.bulk.Command.read_pages', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_pages', full_name='mifare.ultralight.bulk.Command.write_pages', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_counter', full_name='mifare.ultralight.bulk.Command.get_counter', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment_counter', full_name='mifare.ultralight.bulk.Command.increment_counter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_on_clear_key', full_name='mifare.ultralight.bulk.Command.auth_on_clear_key', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_on_sam_key', full_name='mifare.ultralight.bulk.Command.auth_on_sam_key', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_clear_password', full_name='mifare.ultralight.bulk.Command.auth_clear_password', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_sam_password', full_name='mifare.ultralight.bulk.Command.auth_sam_password', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MfrCmd', full_name='mifare.ultralight.bulk.Command.MfrCmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=402,
  serialized_end=954,
)


_COMMANDRESULT = _descriptor.Descriptor(
  name='CommandResult',
  full_name='mifare.ultralight.bulk.CommandResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pages', full_name='mifare.ultralight.bulk.CommandResult.pages', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter_value', full_name='mifare.ultralight.bulk.CommandResult.counter_value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MfrResult', full_name='mifare.ultralight.bulk.CommandResult.MfrResult',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=957,
  serialized_end=1103,
)

_BULKOPERATION.fields_by_name['operations'].message_type = _COMMAND
_BULKRESULT.fields_by_name['results'].message_type = _COMMANDRESULT
_COMMAND.fields_by_name['read_pages'].message_type = mifare_dot_ultralight_dot_read__pb2._READPAGES
_COMMAND.fields_by_name['write_pages'].message_type = mifare_dot_ultralight_dot_write__pb2._WRITEPAGES
_COMMAND.fields_by_name['get_counter'].message_type = mifare_dot_ultralight_dot_counter_dot_get__pb2._GETCOUNTER
_COMMAND.fields_by_name['increment_counter'].message_type = mifare_dot_ultralight_dot_counter_dot_increment__pb2._INCREMENTCOUNTER
_COMMAND.fields_by_name['auth_on_clear_key'].message_type = mifare_dot_ultralight_dot_auth__pb2._CLEARKEY
_COMMAND.fields_by_name['auth_on_sam_key'].message_type = mifare_dot_ultralight_dot_auth__pb2._SAMKEY
_COMMAND.fields_by_name['auth_clear_password'].message_type = mifare_dot_ultralight_dot_password__pb2._CLEARPASSWORD
_COMMAND.fields_by_name['auth_sam_password'].message_type = mifare_dot_ultralight_dot_password__pb2._SAMPASSWORD
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['read_pages'])
_COMMAND.fields_by_name['read_pages'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['write_pages'])
_COMMAND.fields_by_name['write_pages'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['get_counter'])
_COMMAND.fields_by_name['get_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['increment_counter'])
_COMMAND.fields_by_name['increment_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_on_clear_key'])
_COMMAND.fields_by_name['auth_on_clear_key'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_on_sam_key'])
_COMMAND.fields_by_name['auth_on_sam_key'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_clear_password'])
_COMMAND.fields_by_name['auth_clear_password'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_sam_password'])
_COMMAND.fields_by_name['auth_sam_password'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMANDRESULT.fields_by_name['pages'].message_type = mifare_dot_ultralight_dot_read__pb2._PAGES
_COMMANDRESULT.fields_by_name['counter_value'].message_type = mifare_dot_ultralight_dot_counter_dot_get__pb2._COUNTERVALUE
_COMMANDRESULT.oneofs_by_name['MfrResult'].fields.append(
  _COMMANDRESULT.fields_by_name['pages'])
_COMMANDRESULT.fields_by_name['pages'].containing_oneof = _COMMANDRESULT.oneofs_by_name['MfrResult']
_COMMANDRESULT.oneofs_by_name['MfrResult'].fields.append(
  _COMMANDRESULT.fields_by_name['counter_value'])
_COMMANDRESULT.fields_by_name['counter_value'].containing_oneof = _COMMANDRESULT.oneofs_by_name['MfrResult']
DESCRIPTOR.message_types_by_name['BulkOperation'] = _BULKOPERATION
DESCRIPTOR.message_types_by_name['BulkResult'] = _BULKRESULT
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CommandResult'] = _COMMANDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BulkOperation = _reflection.GeneratedProtocolMessageType('BulkOperation', (_message.Message,), dict(
  DESCRIPTOR = _BULKOPERATION,
  __module__ = 'mifare.ultralight.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.bulk.BulkOperation)
  ))
_sym_db.RegisterMessage(BulkOperation)

BulkResult = _reflection.GeneratedProtocolMessageType('BulkResult', (_message.Message,), dict(
  DESCRIPTOR = _BULKRESULT,
  __module__ = 'mifare.ultralight.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.bulk.BulkResult)
  ))
_sym_db.RegisterMessage(BulkResult)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'mifare.ultralight.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.bulk.Command)
  ))
_sym_db.RegisterMessage(Command)

CommandResult = _reflection.GeneratedProtocolMessageType('CommandResult', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDRESULT,
  __module__ = 'mifare.ultralight.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.bulk.CommandResult)
  ))
_sym_db.RegisterMessage(CommandResult)


# @@protoc_insertion_point(module_scope)
