# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/baudrate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/baudrate.proto',
  package='misc.baudrate',
  syntax='proto2',
  serialized_pb=_b('\n\x13misc/baudrate.proto\x12\rmisc.baudrate\";\n\x0e\x43hangeBaudrate\x12)\n\x08\x62\x61udrate\x18\x01 \x02(\x0e\x32\x17.misc.baudrate.Baudrate*J\n\x08\x42\x61udrate\x12\x0e\n\nBPS_115200\x10\x00\x12\x0e\n\nBPS_230400\x10\x01\x12\x0e\n\nBPS_460800\x10\x02\x12\x0e\n\nBPS_921600\x10\x03')
)

_BAUDRATE = _descriptor.EnumDescriptor(
  name='Baudrate',
  full_name='misc.baudrate.Baudrate',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BPS_115200', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BPS_230400', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BPS_460800', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BPS_921600', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=99,
  serialized_end=173,
)
_sym_db.RegisterEnumDescriptor(_BAUDRATE)

Baudrate = enum_type_wrapper.EnumTypeWrapper(_BAUDRATE)
BPS_115200 = 0
BPS_230400 = 1
BPS_460800 = 2
BPS_921600 = 3



_CHANGEBAUDRATE = _descriptor.Descriptor(
  name='ChangeBaudrate',
  full_name='misc.baudrate.ChangeBaudrate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='baudrate', full_name='misc.baudrate.ChangeBaudrate.baudrate', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=97,
)

_CHANGEBAUDRATE.fields_by_name['baudrate'].enum_type = _BAUDRATE
DESCRIPTOR.message_types_by_name['ChangeBaudrate'] = _CHANGEBAUDRATE
DESCRIPTOR.enum_types_by_name['Baudrate'] = _BAUDRATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChangeBaudrate = _reflection.GeneratedProtocolMessageType('ChangeBaudrate', (_message.Message,), dict(
  DESCRIPTOR = _CHANGEBAUDRATE,
  __module__ = 'misc.baudrate_pb2'
  # @@protoc_insertion_point(class_scope:misc.baudrate.ChangeBaudrate)
  ))
_sym_db.RegisterMessage(ChangeBaudrate)


# @@protoc_insertion_point(module_scope)
