# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/lwip.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/lwip.proto',
  package='misc.lwip',
  syntax='proto2',
  serialized_pb=_b('\n\x0fmisc/lwip.proto\x12\tmisc.lwip\"\xa7\x01\n\tStatistic\x12&\n\x04link\x18\x01 \x02(\x0b\x32\x18.misc.lwip.ProtocolStats\x12%\n\x03\x61rp\x18\x02 \x02(\x0b\x32\x18.misc.lwip.ProtocolStats\x12$\n\x02ip\x18\x03 \x02(\x0b\x32\x18.misc.lwip.ProtocolStats\x12%\n\x03tcp\x18\x04 \x02(\x0b\x32\x18.misc.lwip.ProtocolStats\"\xb2\x01\n\rProtocolStats\x12\x0c\n\x04xmit\x18\x01 \x02(\r\x12\x0c\n\x04recv\x18\x02 \x02(\r\x12\n\n\x02\x66w\x18\x03 \x02(\r\x12\x0c\n\x04\x64rop\x18\x04 \x02(\r\x12\x0e\n\x06\x63hkerr\x18\x05 \x02(\r\x12\x0e\n\x06lenerr\x18\x06 \x02(\r\x12\x0e\n\x06memerr\x18\x07 \x02(\r\x12\r\n\x05rterr\x18\x08 \x02(\r\x12\x0f\n\x07proterr\x18\t \x02(\r\x12\x0e\n\x06opterr\x18\n \x02(\r\x12\x0b\n\x03\x65rr\x18\x0b \x02(\r')
)




_STATISTIC = _descriptor.Descriptor(
  name='Statistic',
  full_name='misc.lwip.Statistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='misc.lwip.Statistic.link', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arp', full_name='misc.lwip.Statistic.arp', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='misc.lwip.Statistic.ip', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tcp', full_name='misc.lwip.Statistic.tcp', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=198,
)


_PROTOCOLSTATS = _descriptor.Descriptor(
  name='ProtocolStats',
  full_name='misc.lwip.ProtocolStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xmit', full_name='misc.lwip.ProtocolStats.xmit', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recv', full_name='misc.lwip.ProtocolStats.recv', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fw', full_name='misc.lwip.ProtocolStats.fw', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='drop', full_name='misc.lwip.ProtocolStats.drop', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chkerr', full_name='misc.lwip.ProtocolStats.chkerr', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lenerr', full_name='misc.lwip.ProtocolStats.lenerr', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memerr', full_name='misc.lwip.ProtocolStats.memerr', index=6,
      number=7, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rterr', full_name='misc.lwip.ProtocolStats.rterr', index=7,
      number=8, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proterr', full_name='misc.lwip.ProtocolStats.proterr', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opterr', full_name='misc.lwip.ProtocolStats.opterr', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err', full_name='misc.lwip.ProtocolStats.err', index=10,
      number=11, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=379,
)

_STATISTIC.fields_by_name['link'].message_type = _PROTOCOLSTATS
_STATISTIC.fields_by_name['arp'].message_type = _PROTOCOLSTATS
_STATISTIC.fields_by_name['ip'].message_type = _PROTOCOLSTATS
_STATISTIC.fields_by_name['tcp'].message_type = _PROTOCOLSTATS
DESCRIPTOR.message_types_by_name['Statistic'] = _STATISTIC
DESCRIPTOR.message_types_by_name['ProtocolStats'] = _PROTOCOLSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Statistic = _reflection.GeneratedProtocolMessageType('Statistic', (_message.Message,), dict(
  DESCRIPTOR = _STATISTIC,
  __module__ = 'misc.lwip_pb2'
  # @@protoc_insertion_point(class_scope:misc.lwip.Statistic)
  ))
_sym_db.RegisterMessage(Statistic)

ProtocolStats = _reflection.GeneratedProtocolMessageType('ProtocolStats', (_message.Message,), dict(
  DESCRIPTOR = _PROTOCOLSTATS,
  __module__ = 'misc.lwip_pb2'
  # @@protoc_insertion_point(class_scope:misc.lwip.ProtocolStats)
  ))
_sym_db.RegisterMessage(ProtocolStats)


# @@protoc_insertion_point(module_scope)
