# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/reboot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/reboot.proto',
  package='misc.reboot',
  syntax='proto2',
  serialized_pb=_b('\n\x11misc/reboot.proto\x12\x0bmisc.reboot\"\x8f\x01\n\x06Reboot\x12<\n\x04mode\x18\x01 \x01(\x0e\x32!.misc.reboot.Reboot.OperationMode:\x0bNORMAL_MODE\"G\n\rOperationMode\x12\x0f\n\x0bNORMAL_MODE\x10\x00\x12\x13\n\x0fMANAGEMENT_MODE\x10\x01\x12\x10\n\x0c\x46\x41\x43TORY_MODE\x10\x02')
)



_REBOOT_OPERATIONMODE = _descriptor.EnumDescriptor(
  name='OperationMode',
  full_name='misc.reboot.Reboot.OperationMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL_MODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MANAGEMENT_MODE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FACTORY_MODE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=107,
  serialized_end=178,
)
_sym_db.RegisterEnumDescriptor(_REBOOT_OPERATIONMODE)


_REBOOT = _descriptor.Descriptor(
  name='Reboot',
  full_name='misc.reboot.Reboot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='misc.reboot.Reboot.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REBOOT_OPERATIONMODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=178,
)

_REBOOT.fields_by_name['mode'].enum_type = _REBOOT_OPERATIONMODE
_REBOOT_OPERATIONMODE.containing_type = _REBOOT
DESCRIPTOR.message_types_by_name['Reboot'] = _REBOOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reboot = _reflection.GeneratedProtocolMessageType('Reboot', (_message.Message,), dict(
  DESCRIPTOR = _REBOOT,
  __module__ = 'misc.reboot_pb2'
  # @@protoc_insertion_point(class_scope:misc.reboot.Reboot)
  ))
_sym_db.RegisterMessage(Reboot)


# @@protoc_insertion_point(module_scope)
