# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from misc import lwip_pb2 as misc_dot_lwip__pb2
from misc import event_pb2 as misc_dot_event__pb2
from misc import ethernet_pb2 as misc_dot_ethernet__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/stats.proto',
  package='misc.stats',
  syntax='proto2',
  serialized_pb=_b('\n\x10misc/stats.proto\x12\nmisc.stats\x1a\x0fmisc/lwip.proto\x1a\x10misc/event.proto\x1a\x13misc/ethernet.proto\"\x14\n\x12GetDeviceStatistic\"\x84\x01\n\x0f\x44\x65viceStatistic\x12\"\n\x04lwip\x18\x01 \x01(\x0b\x32\x14.misc.lwip.Statistic\x12!\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x11.misc.event.Event\x12*\n\x08\x65thernet\x18\x03 \x01(\x0b\x32\x18.misc.ethernet.Statistic')
  ,
  dependencies=[misc_dot_lwip__pb2.DESCRIPTOR,misc_dot_event__pb2.DESCRIPTOR,misc_dot_ethernet__pb2.DESCRIPTOR,])




_GETDEVICESTATISTIC = _descriptor.Descriptor(
  name='GetDeviceStatistic',
  full_name='misc.stats.GetDeviceStatistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=108,
)


_DEVICESTATISTIC = _descriptor.Descriptor(
  name='DeviceStatistic',
  full_name='misc.stats.DeviceStatistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lwip', full_name='misc.stats.DeviceStatistic.lwip', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='misc.stats.DeviceStatistic.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ethernet', full_name='misc.stats.DeviceStatistic.ethernet', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=243,
)

_DEVICESTATISTIC.fields_by_name['lwip'].message_type = misc_dot_lwip__pb2._STATISTIC
_DEVICESTATISTIC.fields_by_name['events'].message_type = misc_dot_event__pb2._EVENT
_DEVICESTATISTIC.fields_by_name['ethernet'].message_type = misc_dot_ethernet__pb2._STATISTIC
DESCRIPTOR.message_types_by_name['GetDeviceStatistic'] = _GETDEVICESTATISTIC
DESCRIPTOR.message_types_by_name['DeviceStatistic'] = _DEVICESTATISTIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetDeviceStatistic = _reflection.GeneratedProtocolMessageType('GetDeviceStatistic', (_message.Message,), dict(
  DESCRIPTOR = _GETDEVICESTATISTIC,
  __module__ = 'misc.stats_pb2'
  # @@protoc_insertion_point(class_scope:misc.stats.GetDeviceStatistic)
  ))
_sym_db.RegisterMessage(GetDeviceStatistic)

DeviceStatistic = _reflection.GeneratedProtocolMessageType('DeviceStatistic', (_message.Message,), dict(
  DESCRIPTOR = _DEVICESTATISTIC,
  __module__ = 'misc.stats_pb2'
  # @@protoc_insertion_point(class_scope:misc.stats.DeviceStatistic)
  ))
_sym_db.RegisterMessage(DeviceStatistic)


# @@protoc_insertion_point(module_scope)
