# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/append_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/append_record.proto',
  package='cipurse.append_record',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x63ipurse/append_record.proto\x12\x15\x63ipurse.append_record\"3\n\x0c\x41ppendRecord\x12\x15\n\rshort_file_id\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c')
)




_APPENDRECORD = _descriptor.Descriptor(
  name='AppendRecord',
  full_name='cipurse.append_record.AppendRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_file_id', full_name='cipurse.append_record.AppendRecord.short_file_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cipurse.append_record.AppendRecord.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['AppendRecord'] = _APPENDRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppendRecord = _reflection.GeneratedProtocolMessageType('AppendRecord', (_message.Message,), dict(
  DESCRIPTOR = _APPENDRECORD,
  __module__ = 'cipurse.append_record_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.append_record.AppendRecord)
  ))
_sym_db.RegisterMessage(AppendRecord)


# @@protoc_insertion_point(module_scope)
