# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contact import card_slot_pb2 as contact_dot_card__slot__pb2
from cipurse import security_level_pb2 as cipurse_dot_security__level__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/auth.proto',
  package='cipurse.auth',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x63ipurse/auth.proto\x12\x0c\x63ipurse.auth\x1a\x17\x63ontact/card_slot.proto\x1a\x1c\x63ipurse/security_level.proto\"\xd3\x01\n\x16\x45stablishSecureChannel\x12\x12\n\nkey_number\x18\x01 \x02(\r\x12\x12\n\nsam_key_id\x18\x02 \x02(\r\x12\x1c\n\x14\x64iversification_data\x18\x03 \x01(\x0c\x12)\n\x04slot\x18\x04 \x01(\x0e\x32\x1b.contact.card_slot.CardSlot\x12H\n\x0esecurity_level\x18\x05 \x01(\x0e\x32%.cipurse.security_level.SecurityLevel:\tENCRYPTED')
  ,
  dependencies=[contact_dot_card__slot__pb2.DESCRIPTOR,cipurse_dot_security__level__pb2.DESCRIPTOR,])




_ESTABLISHSECURECHANNEL = _descriptor.Descriptor(
  name='EstablishSecureChannel',
  full_name='cipurse.auth.EstablishSecureChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_number', full_name='cipurse.auth.EstablishSecureChannel.key_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sam_key_id', full_name='cipurse.auth.EstablishSecureChannel.sam_key_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diversification_data', full_name='cipurse.auth.EstablishSecureChannel.diversification_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot', full_name='cipurse.auth.EstablishSecureChannel.slot', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='security_level', full_name='cipurse.auth.EstablishSecureChannel.security_level', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=303,
)

_ESTABLISHSECURECHANNEL.fields_by_name['slot'].enum_type = contact_dot_card__slot__pb2._CARDSLOT
_ESTABLISHSECURECHANNEL.fields_by_name['security_level'].enum_type = cipurse_dot_security__level__pb2._SECURITYLEVEL
DESCRIPTOR.message_types_by_name['EstablishSecureChannel'] = _ESTABLISHSECURECHANNEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstablishSecureChannel = _reflection.GeneratedProtocolMessageType('EstablishSecureChannel', (_message.Message,), dict(
  DESCRIPTOR = _ESTABLISHSECURECHANNEL,
  __module__ = 'cipurse.auth_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.auth.EstablishSecureChannel)
  ))
_sym_db.RegisterMessage(EstablishSecureChannel)


# @@protoc_insertion_point(module_scope)
