# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/authorize_sam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contact import card_slot_pb2 as contact_dot_card__slot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/authorize_sam.proto',
  package='cipurse.sam',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x63ipurse/authorize_sam.proto\x12\x0b\x63ipurse.sam\x1a\x17\x63ontact/card_slot.proto\"Z\n\x0e\x41uthorizeHwSam\x12)\n\x04slot\x18\x01 \x02(\x0e\x32\x1b.contact.card_slot.CardSlot\x12\x0b\n\x03\x61id\x18\x02 \x02(\x0c\x12\x10\n\x08password\x18\x03 \x01(\x0c')
  ,
  dependencies=[contact_dot_card__slot__pb2.DESCRIPTOR,])




_AUTHORIZEHWSAM = _descriptor.Descriptor(
  name='AuthorizeHwSam',
  full_name='cipurse.sam.AuthorizeHwSam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slot', full_name='cipurse.sam.AuthorizeHwSam.slot', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aid', full_name='cipurse.sam.AuthorizeHwSam.aid', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='cipurse.sam.AuthorizeHwSam.password', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=159,
)

_AUTHORIZEHWSAM.fields_by_name['slot'].enum_type = contact_dot_card__slot__pb2._CARDSLOT
DESCRIPTOR.message_types_by_name['AuthorizeHwSam'] = _AUTHORIZEHWSAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AuthorizeHwSam = _reflection.GeneratedProtocolMessageType('AuthorizeHwSam', (_message.Message,), dict(
  DESCRIPTOR = _AUTHORIZEHWSAM,
  __module__ = 'cipurse.authorize_sam_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.sam.AuthorizeHwSam)
  ))
_sym_db.RegisterMessage(AuthorizeHwSam)


# @@protoc_insertion_point(module_scope)
