# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/read_binary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/read_binary.proto',
  package='cipurse.read_binary',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x63ipurse/read_binary.proto\x12\x13\x63ipurse.read_binary\"F\n\nReadBinary\x12\x15\n\rshort_file_id\x18\x01 \x02(\r\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x11\n\x06offset\x18\x03 \x01(\r:\x01\x30\"\x16\n\x06\x42inary\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')
)




_READBINARY = _descriptor.Descriptor(
  name='ReadBinary',
  full_name='cipurse.read_binary.ReadBinary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_file_id', full_name='cipurse.read_binary.ReadBinary.short_file_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='cipurse.read_binary.ReadBinary.length', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='cipurse.read_binary.ReadBinary.offset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=120,
)


_BINARY = _descriptor.Descriptor(
  name='Binary',
  full_name='cipurse.read_binary.Binary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cipurse.read_binary.Binary.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['ReadBinary'] = _READBINARY
DESCRIPTOR.message_types_by_name['Binary'] = _BINARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadBinary = _reflection.GeneratedProtocolMessageType('ReadBinary', (_message.Message,), dict(
  DESCRIPTOR = _READBINARY,
  __module__ = 'cipurse.read_binary_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.read_binary.ReadBinary)
  ))
_sym_db.RegisterMessage(ReadBinary)

Binary = _reflection.GeneratedProtocolMessageType('Binary', (_message.Message,), dict(
  DESCRIPTOR = _BINARY,
  __module__ = 'cipurse.read_binary_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.read_binary.Binary)
  ))
_sym_db.RegisterMessage(Binary)


# @@protoc_insertion_point(module_scope)
