# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/read_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/read_record.proto',
  package='cipurse.read_record',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x63ipurse/read_record.proto\x12\x13\x63ipurse.read_record\"r\n\nReadRecord\x12\x15\n\rshort_file_id\x18\x01 \x02(\r\x12\x0e\n\x06length\x18\x02 \x02(\r\x12\x17\n\x0c\x66irst_record\x18\x03 \x01(\r:\x01\x31\x12$\n\x15read_multiple_records\x18\x04 \x01(\x08:\x05\x66\x61lse\"\x16\n\x06Record\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')
)




_READRECORD = _descriptor.Descriptor(
  name='ReadRecord',
  full_name='cipurse.read_record.ReadRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_file_id', full_name='cipurse.read_record.ReadRecord.short_file_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='cipurse.read_record.ReadRecord.length', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_record', full_name='cipurse.read_record.ReadRecord.first_record', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_multiple_records', full_name='cipurse.read_record.ReadRecord.read_multiple_records', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=164,
)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='cipurse.read_record.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='cipurse.read_record.Record.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=188,
)

DESCRIPTOR.message_types_by_name['ReadRecord'] = _READRECORD
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadRecord = _reflection.GeneratedProtocolMessageType('ReadRecord', (_message.Message,), dict(
  DESCRIPTOR = _READRECORD,
  __module__ = 'cipurse.read_record_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.read_record.ReadRecord)
  ))
_sym_db.RegisterMessage(ReadRecord)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(
  DESCRIPTOR = _RECORD,
  __module__ = 'cipurse.read_record_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.read_record.Record)
  ))
_sym_db.RegisterMessage(Record)


# @@protoc_insertion_point(module_scope)
