# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/select.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/select.proto',
  package='cipurse.select',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x63ipurse/select.proto\x12\x0e\x63ipurse.select\";\n\nSelectFile\x12\r\n\x03\x61id\x18\x01 \x01(\x0cH\x00\x12\x11\n\x07\x66ile_id\x18\x02 \x01(\rH\x00\x42\x0b\n\tselect_by')
)




_SELECTFILE = _descriptor.Descriptor(
  name='SelectFile',
  full_name='cipurse.select.SelectFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='cipurse.select.SelectFile.aid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_id', full_name='cipurse.select.SelectFile.file_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='select_by', full_name='cipurse.select.SelectFile.select_by',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=40,
  serialized_end=99,
)

_SELECTFILE.oneofs_by_name['select_by'].fields.append(
  _SELECTFILE.fields_by_name['aid'])
_SELECTFILE.fields_by_name['aid'].containing_oneof = _SELECTFILE.oneofs_by_name['select_by']
_SELECTFILE.oneofs_by_name['select_by'].fields.append(
  _SELECTFILE.fields_by_name['file_id'])
_SELECTFILE.fields_by_name['file_id'].containing_oneof = _SELECTFILE.oneofs_by_name['select_by']
DESCRIPTOR.message_types_by_name['SelectFile'] = _SELECTFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SelectFile = _reflection.GeneratedProtocolMessageType('SelectFile', (_message.Message,), dict(
  DESCRIPTOR = _SELECTFILE,
  __module__ = 'cipurse.select_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.select.SelectFile)
  ))
_sym_db.RegisterMessage(SelectFile)


# @@protoc_insertion_point(module_scope)
