# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/update_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/update_record.proto',
  package='cipurse.update_record',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x63ipurse/update_record.proto\x12\x15\x63ipurse.update_record\"t\n\x0cUpdateRecord\x12\x15\n\rshort_file_id\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12\x17\n\x0c\x66irst_record\x18\x03 \x01(\r:\x01\x31\x12&\n\x17update_multiple_records\x18\x04 \x01(\x08:\x05\x66\x61lse')
)




_UPDATERECORD = _descriptor.Descriptor(
  name='UpdateRecord',
  full_name='cipurse.update_record.UpdateRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_file_id', full_name='cipurse.update_record.UpdateRecord.short_file_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cipurse.update_record.UpdateRecord.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_record', full_name='cipurse.update_record.UpdateRecord.first_record', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_multiple_records', full_name='cipurse.update_record.UpdateRecord.update_multiple_records', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['UpdateRecord'] = _UPDATERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateRecord = _reflection.GeneratedProtocolMessageType('UpdateRecord', (_message.Message,), dict(
  DESCRIPTOR = _UPDATERECORD,
  __module__ = 'cipurse.update_record_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.update_record.UpdateRecord)
  ))
_sym_db.RegisterMessage(UpdateRecord)


# @@protoc_insertion_point(module_scope)
