# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cipurse/update_binary.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cipurse/update_binary.proto',
  package='cipurse.update_binary',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x63ipurse/update_binary.proto\x12\x15\x63ipurse.update_binary\"F\n\x0cUpdateBinary\x12\x15\n\rshort_file_id\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12\x11\n\x06offset\x18\x03 \x01(\r:\x01\x30')
)




_UPDATEBINARY = _descriptor.Descriptor(
  name='UpdateBinary',
  full_name='cipurse.update_binary.UpdateBinary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_file_id', full_name='cipurse.update_binary.UpdateBinary.short_file_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='cipurse.update_binary.UpdateBinary.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='cipurse.update_binary.UpdateBinary.offset', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['UpdateBinary'] = _UPDATEBINARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateBinary = _reflection.GeneratedProtocolMessageType('UpdateBinary', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEBINARY,
  __module__ = 'cipurse.update_binary_pb2'
  # @@protoc_insertion_point(class_scope:cipurse.update_binary.UpdateBinary)
  ))
_sym_db.RegisterMessage(UpdateBinary)


# @@protoc_insertion_point(module_scope)
