# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex/poll_for_event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contactless import poll_for_token_pb2 as contactless_dot_poll__for__token__pb2
from contactless import token_pb2 as contactless_dot_token__pb2
from contactless import transaction_pb2 as contactless_dot_transaction__pb2
from gui import screen_pb2 as gui_dot_screen__pb2
from misc import leds_pb2 as misc_dot_leds__pb2
from qrcode import poll_for_qrcode_pb2 as qrcode_dot_poll__for__qrcode__pb2
from qrcode import qrcode_event_pb2 as qrcode_dot_qrcode__event__pb2
from touchscreen import poll_touchscreen_pb2 as touchscreen_dot_poll__touchscreen__pb2
from touchscreen import touchscreen_event_pb2 as touchscreen_dot_touchscreen__event__pb2
from troika.av3 import read_ticket_pb2 as troika_dot_av3_dot_read__ticket__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='complex/poll_for_event.proto',
  package='complex.poll',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x63omplex/poll_for_event.proto\x12\x0c\x63omplex.poll\x1a contactless/poll_for_token.proto\x1a\x17\x63ontactless/token.proto\x1a\x1d\x63ontactless/transaction.proto\x1a\x10gui/screen.proto\x1a\x0fmisc/leds.proto\x1a\x1cqrcode/poll_for_qrcode.proto\x1a\x19qrcode/qrcode_event.proto\x1a\"touchscreen/poll_touchscreen.proto\x1a#touchscreen/touchscreen_event.proto\x1a\x1ctroika/av3/read_ticket.proto\"\xbf\x03\n\x0cPollForEvent\x12\x38\n\x0epoll_for_token\x18\x01 \x01(\x0b\x32\x1e.contactless.poll.PollForTokenH\x00\x12\x42\n\x0bperform_txn\x18\x02 \x01(\x0b\x32+.contactless.transaction.PerformTransactionH\x00\x12;\n\x10poll_touchscreen\x18\x03 \x01(\x0b\x32!.touchscreen.poll.PollTouchscreen\x12\x33\n\x0fpoll_for_qrcode\x18\x04 \x01(\x0b\x32\x1a.qrcode.poll.PollForQrCode\x12\x37\n\x12on_start_ui_action\x18\x05 \x01(\x0b\x32\x1b.complex.poll.UserInterface\x12\x37\n\x12on_event_ui_action\x18\x06 \x01(\x0b\x32\x1b.complex.poll.UserInterface\x12>\n\x16on_mifare_card_present\x18\x07 \x01(\x0b\x32\x1e.complex.poll.MifareCardActionB\r\n\x0b\x63ontactless\"e\n\rUserInterface\x12\'\n\x0eset_leds_state\x18\x01 \x01(\x0b\x32\x0f.misc.leds.Leds\x12+\n\x0bshow_screen\x18\x02 \x01(\x0b\x32\x16.gui.screen.ShowScreen\"b\n\x10MifareCardAction\x12\x44\n\x16troika_av3_read_ticket\x18\x01 \x01(\x0b\x32\".troika.av3.read_ticket.ReadTicketH\x00\x42\x08\n\x06\x61\x63tion\"\xbd\x02\n\x05\x45vent\x12\x35\n\x11\x63ontactless_token\x18\x01 \x01(\x0b\x32\x18.contactless.token.TokenH\x00\x12L\n\x16\x63ontactless_txn_result\x18\x02 \x01(\x0b\x32*.contactless.transaction.TransactionResultH\x00\x12@\n\x11touchscreen_event\x18\x03 \x01(\x0b\x32#.touchscreen.event.TouchscreenEventH\x00\x12+\n\x06qrcode\x18\x04 \x01(\x0b\x32\x19.qrcode.event.QrCodeEventH\x00\x12\x37\n\rtroika_ticket\x18\x05 \x01(\x0b\x32\x1e.troika.av3.read_ticket.TicketH\x00\x42\x07\n\x05\x65vent')
  ,
  dependencies=[contactless_dot_poll__for__token__pb2.DESCRIPTOR,contactless_dot_token__pb2.DESCRIPTOR,contactless_dot_transaction__pb2.DESCRIPTOR,gui_dot_screen__pb2.DESCRIPTOR,misc_dot_leds__pb2.DESCRIPTOR,qrcode_dot_poll__for__qrcode__pb2.DESCRIPTOR,qrcode_dot_qrcode__event__pb2.DESCRIPTOR,touchscreen_dot_poll__touchscreen__pb2.DESCRIPTOR,touchscreen_dot_touchscreen__event__pb2.DESCRIPTOR,troika_dot_av3_dot_read__ticket__pb2.DESCRIPTOR,])




_POLLFOREVENT = _descriptor.Descriptor(
  name='PollForEvent',
  full_name='complex.poll.PollForEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='poll_for_token', full_name='complex.poll.PollForEvent.poll_for_token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perform_txn', full_name='complex.poll.PollForEvent.perform_txn', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poll_touchscreen', full_name='complex.poll.PollForEvent.poll_touchscreen', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='poll_for_qrcode', full_name='complex.poll.PollForEvent.poll_for_qrcode', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_start_ui_action', full_name='complex.poll.PollForEvent.on_start_ui_action', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_event_ui_action', full_name='complex.poll.PollForEvent.on_event_ui_action', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='on_mifare_card_present', full_name='complex.poll.PollForEvent.on_mifare_card_present', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='contactless', full_name='complex.poll.PollForEvent.contactless',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=332,
  serialized_end=779,
)


_USERINTERFACE = _descriptor.Descriptor(
  name='UserInterface',
  full_name='complex.poll.UserInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_leds_state', full_name='complex.poll.UserInterface.set_leds_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_screen', full_name='complex.poll.UserInterface.show_screen', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=781,
  serialized_end=882,
)


_MIFARECARDACTION = _descriptor.Descriptor(
  name='MifareCardAction',
  full_name='complex.poll.MifareCardAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='troika_av3_read_ticket', full_name='complex.poll.MifareCardAction.troika_av3_read_ticket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='action', full_name='complex.poll.MifareCardAction.action',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=884,
  serialized_end=982,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='complex.poll.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contactless_token', full_name='complex.poll.Event.contactless_token', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contactless_txn_result', full_name='complex.poll.Event.contactless_txn_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='touchscreen_event', full_name='complex.poll.Event.touchscreen_event', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qrcode', full_name='complex.poll.Event.qrcode', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='troika_ticket', full_name='complex.poll.Event.troika_ticket', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='event', full_name='complex.poll.Event.event',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=985,
  serialized_end=1302,
)

_POLLFOREVENT.fields_by_name['poll_for_token'].message_type = contactless_dot_poll__for__token__pb2._POLLFORTOKEN
_POLLFOREVENT.fields_by_name['perform_txn'].message_type = contactless_dot_transaction__pb2._PERFORMTRANSACTION
_POLLFOREVENT.fields_by_name['poll_touchscreen'].message_type = touchscreen_dot_poll__touchscreen__pb2._POLLTOUCHSCREEN
_POLLFOREVENT.fields_by_name['poll_for_qrcode'].message_type = qrcode_dot_poll__for__qrcode__pb2._POLLFORQRCODE
_POLLFOREVENT.fields_by_name['on_start_ui_action'].message_type = _USERINTERFACE
_POLLFOREVENT.fields_by_name['on_event_ui_action'].message_type = _USERINTERFACE
_POLLFOREVENT.fields_by_name['on_mifare_card_present'].message_type = _MIFARECARDACTION
_POLLFOREVENT.oneofs_by_name['contactless'].fields.append(
  _POLLFOREVENT.fields_by_name['poll_for_token'])
_POLLFOREVENT.fields_by_name['poll_for_token'].containing_oneof = _POLLFOREVENT.oneofs_by_name['contactless']
_POLLFOREVENT.oneofs_by_name['contactless'].fields.append(
  _POLLFOREVENT.fields_by_name['perform_txn'])
_POLLFOREVENT.fields_by_name['perform_txn'].containing_oneof = _POLLFOREVENT.oneofs_by_name['contactless']
_USERINTERFACE.fields_by_name['set_leds_state'].message_type = misc_dot_leds__pb2._LEDS
_USERINTERFACE.fields_by_name['show_screen'].message_type = gui_dot_screen__pb2._SHOWSCREEN
_MIFARECARDACTION.fields_by_name['troika_av3_read_ticket'].message_type = troika_dot_av3_dot_read__ticket__pb2._READTICKET
_MIFARECARDACTION.oneofs_by_name['action'].fields.append(
  _MIFARECARDACTION.fields_by_name['troika_av3_read_ticket'])
_MIFARECARDACTION.fields_by_name['troika_av3_read_ticket'].containing_oneof = _MIFARECARDACTION.oneofs_by_name['action']
_EVENT.fields_by_name['contactless_token'].message_type = contactless_dot_token__pb2._TOKEN
_EVENT.fields_by_name['contactless_txn_result'].message_type = contactless_dot_transaction__pb2._TRANSACTIONRESULT
_EVENT.fields_by_name['touchscreen_event'].message_type = touchscreen_dot_touchscreen__event__pb2._TOUCHSCREENEVENT
_EVENT.fields_by_name['qrcode'].message_type = qrcode_dot_qrcode__event__pb2._QRCODEEVENT
_EVENT.fields_by_name['troika_ticket'].message_type = troika_dot_av3_dot_read__ticket__pb2._TICKET
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['contactless_token'])
_EVENT.fields_by_name['contactless_token'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['contactless_txn_result'])
_EVENT.fields_by_name['contactless_txn_result'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['touchscreen_event'])
_EVENT.fields_by_name['touchscreen_event'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['qrcode'])
_EVENT.fields_by_name['qrcode'].containing_oneof = _EVENT.oneofs_by_name['event']
_EVENT.oneofs_by_name['event'].fields.append(
  _EVENT.fields_by_name['troika_ticket'])
_EVENT.fields_by_name['troika_ticket'].containing_oneof = _EVENT.oneofs_by_name['event']
DESCRIPTOR.message_types_by_name['PollForEvent'] = _POLLFOREVENT
DESCRIPTOR.message_types_by_name['UserInterface'] = _USERINTERFACE
DESCRIPTOR.message_types_by_name['MifareCardAction'] = _MIFARECARDACTION
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PollForEvent = _reflection.GeneratedProtocolMessageType('PollForEvent', (_message.Message,), dict(
  DESCRIPTOR = _POLLFOREVENT,
  __module__ = 'complex.poll_for_event_pb2'
  # @@protoc_insertion_point(class_scope:complex.poll.PollForEvent)
  ))
_sym_db.RegisterMessage(PollForEvent)

UserInterface = _reflection.GeneratedProtocolMessageType('UserInterface', (_message.Message,), dict(
  DESCRIPTOR = _USERINTERFACE,
  __module__ = 'complex.poll_for_event_pb2'
  # @@protoc_insertion_point(class_scope:complex.poll.UserInterface)
  ))
_sym_db.RegisterMessage(UserInterface)

MifareCardAction = _reflection.GeneratedProtocolMessageType('MifareCardAction', (_message.Message,), dict(
  DESCRIPTOR = _MIFARECARDACTION,
  __module__ = 'complex.poll_for_event_pb2'
  # @@protoc_insertion_point(class_scope:complex.poll.MifareCardAction)
  ))
_sym_db.RegisterMessage(MifareCardAction)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'complex.poll_for_event_pb2'
  # @@protoc_insertion_point(class_scope:complex.poll.Event)
  ))
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
