# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turnstile/passage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='turnstile/passage.proto',
  package='turnstile.passage',
  syntax='proto2',
  serialized_pb=_b('\n\x17turnstile/passage.proto\x12\x11turnstile.passage\"\x9b\x01\n\x0c\x41llowOnePass\x12\x12\n\ntimeout_ms\x18\x01 \x02(\r\x12\x32\n\nhold_level\x18\x02 \x01(\x0b\x32\x1c.turnstile.passage.HoldLevelH\x00\x12\x34\n\x0bone_impulse\x18\x03 \x01(\x0b\x32\x1d.turnstile.passage.OneImpulseH\x00\x42\r\n\x0bopen_signal\"\x0b\n\tHoldLevel\"!\n\nOneImpulse\x12\x13\n\x0b\x64uration_ms\x18\x01 \x02(\r')
)




_ALLOWONEPASS = _descriptor.Descriptor(
  name='AllowOnePass',
  full_name='turnstile.passage.AllowOnePass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout_ms', full_name='turnstile.passage.AllowOnePass.timeout_ms', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hold_level', full_name='turnstile.passage.AllowOnePass.hold_level', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='one_impulse', full_name='turnstile.passage.AllowOnePass.one_impulse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='open_signal', full_name='turnstile.passage.AllowOnePass.open_signal',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=202,
)


_HOLDLEVEL = _descriptor.Descriptor(
  name='HoldLevel',
  full_name='turnstile.passage.HoldLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=215,
)


_ONEIMPULSE = _descriptor.Descriptor(
  name='OneImpulse',
  full_name='turnstile.passage.OneImpulse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration_ms', full_name='turnstile.passage.OneImpulse.duration_ms', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=250,
)

_ALLOWONEPASS.fields_by_name['hold_level'].message_type = _HOLDLEVEL
_ALLOWONEPASS.fields_by_name['one_impulse'].message_type = _ONEIMPULSE
_ALLOWONEPASS.oneofs_by_name['open_signal'].fields.append(
  _ALLOWONEPASS.fields_by_name['hold_level'])
_ALLOWONEPASS.fields_by_name['hold_level'].containing_oneof = _ALLOWONEPASS.oneofs_by_name['open_signal']
_ALLOWONEPASS.oneofs_by_name['open_signal'].fields.append(
  _ALLOWONEPASS.fields_by_name['one_impulse'])
_ALLOWONEPASS.fields_by_name['one_impulse'].containing_oneof = _ALLOWONEPASS.oneofs_by_name['open_signal']
DESCRIPTOR.message_types_by_name['AllowOnePass'] = _ALLOWONEPASS
DESCRIPTOR.message_types_by_name['HoldLevel'] = _HOLDLEVEL
DESCRIPTOR.message_types_by_name['OneImpulse'] = _ONEIMPULSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AllowOnePass = _reflection.GeneratedProtocolMessageType('AllowOnePass', (_message.Message,), dict(
  DESCRIPTOR = _ALLOWONEPASS,
  __module__ = 'turnstile.passage_pb2'
  # @@protoc_insertion_point(class_scope:turnstile.passage.AllowOnePass)
  ))
_sym_db.RegisterMessage(AllowOnePass)

HoldLevel = _reflection.GeneratedProtocolMessageType('HoldLevel', (_message.Message,), dict(
  DESCRIPTOR = _HOLDLEVEL,
  __module__ = 'turnstile.passage_pb2'
  # @@protoc_insertion_point(class_scope:turnstile.passage.HoldLevel)
  ))
_sym_db.RegisterMessage(HoldLevel)

OneImpulse = _reflection.GeneratedProtocolMessageType('OneImpulse', (_message.Message,), dict(
  DESCRIPTOR = _ONEIMPULSE,
  __module__ = 'turnstile.passage_pb2'
  # @@protoc_insertion_point(class_scope:turnstile.passage.OneImpulse)
  ))
_sym_db.RegisterMessage(OneImpulse)


# @@protoc_insertion_point(module_scope)
