# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv/challenge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv/challenge.proto',
  package='srv.challenge',
  syntax='proto2',
  serialized_pb=_b('\n\x13srv/challenge.proto\x12\rsrv.challenge\"\x1c\n\x0cGetChallenge\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\x19\n\tChallenge\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')
)




_GETCHALLENGE = _descriptor.Descriptor(
  name='GetChallenge',
  full_name='srv.challenge.GetChallenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='srv.challenge.GetChallenge.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=66,
)


_CHALLENGE = _descriptor.Descriptor(
  name='Challenge',
  full_name='srv.challenge.Challenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='srv.challenge.Challenge.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['GetChallenge'] = _GETCHALLENGE
DESCRIPTOR.message_types_by_name['Challenge'] = _CHALLENGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetChallenge = _reflection.GeneratedProtocolMessageType('GetChallenge', (_message.Message,), dict(
  DESCRIPTOR = _GETCHALLENGE,
  __module__ = 'srv.challenge_pb2'
  # @@protoc_insertion_point(class_scope:srv.challenge.GetChallenge)
  ))
_sym_db.RegisterMessage(GetChallenge)

Challenge = _reflection.GeneratedProtocolMessageType('Challenge', (_message.Message,), dict(
  DESCRIPTOR = _CHALLENGE,
  __module__ = 'srv.challenge_pb2'
  # @@protoc_insertion_point(class_scope:srv.challenge.Challenge)
  ))
_sym_db.RegisterMessage(Challenge)


# @@protoc_insertion_point(module_scope)
