# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv/protection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv/protection.proto',
  package='srv.protection',
  syntax='proto2',
  serialized_pb=_b('\n\x14srv/protection.proto\x12\x0esrv.protection\"\'\n\x08\x41\x63tivate\x12\x1b\n\x13\x65ncrypted_challenge\x18\x01 \x02(\x0c\"\x0c\n\nDeactivate')
)




_ACTIVATE = _descriptor.Descriptor(
  name='Activate',
  full_name='srv.protection.Activate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='encrypted_challenge', full_name='srv.protection.Activate.encrypted_challenge', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=79,
)


_DEACTIVATE = _descriptor.Descriptor(
  name='Deactivate',
  full_name='srv.protection.Deactivate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['Activate'] = _ACTIVATE
DESCRIPTOR.message_types_by_name['Deactivate'] = _DEACTIVATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Activate = _reflection.GeneratedProtocolMessageType('Activate', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVATE,
  __module__ = 'srv.protection_pb2'
  # @@protoc_insertion_point(class_scope:srv.protection.Activate)
  ))
_sym_db.RegisterMessage(Activate)

Deactivate = _reflection.GeneratedProtocolMessageType('Deactivate', (_message.Message,), dict(
  DESCRIPTOR = _DEACTIVATE,
  __module__ = 'srv.protection_pb2'
  # @@protoc_insertion_point(class_scope:srv.protection.Deactivate)
  ))
_sym_db.RegisterMessage(Deactivate)


# @@protoc_insertion_point(module_scope)
