# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: srv/upload_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='srv/upload_config.proto',
  package='srv.upload_config',
  syntax='proto2',
  serialized_pb=_b('\n\x17srv/upload_config.proto\x12\x11srv.upload_config\"\x1e\n\x07Prepare\x12\x13\n\x0b\x63onfig_size\x18\x01 \x02(\r\"\x1b\n\x0bUploadBlock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\x14\n\x12\x43heckConfiguration\"F\n\rConfiguration\x12&\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x17.srv.upload_config.File\x12\r\n\x05\x63rc32\x18\x02 \x01(\r\"1\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0c\n\x04size\x18\x02 \x02(\r\x12\r\n\x05\x63rc32\x18\x03 \x02(\r')
)




_PREPARE = _descriptor.Descriptor(
  name='Prepare',
  full_name='srv.upload_config.Prepare',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config_size', full_name='srv.upload_config.Prepare.config_size', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=76,
)


_UPLOADBLOCK = _descriptor.Descriptor(
  name='UploadBlock',
  full_name='srv.upload_config.UploadBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='srv.upload_config.UploadBlock.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=105,
)


_CHECKCONFIGURATION = _descriptor.Descriptor(
  name='CheckConfiguration',
  full_name='srv.upload_config.CheckConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=127,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='srv.upload_config.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='srv.upload_config.Configuration.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crc32', full_name='srv.upload_config.Configuration.crc32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=199,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='srv.upload_config.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='srv.upload_config.File.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='srv.upload_config.File.size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crc32', full_name='srv.upload_config.File.crc32', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=250,
)

_CONFIGURATION.fields_by_name['files'].message_type = _FILE
DESCRIPTOR.message_types_by_name['Prepare'] = _PREPARE
DESCRIPTOR.message_types_by_name['UploadBlock'] = _UPLOADBLOCK
DESCRIPTOR.message_types_by_name['CheckConfiguration'] = _CHECKCONFIGURATION
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['File'] = _FILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Prepare = _reflection.GeneratedProtocolMessageType('Prepare', (_message.Message,), dict(
  DESCRIPTOR = _PREPARE,
  __module__ = 'srv.upload_config_pb2'
  # @@protoc_insertion_point(class_scope:srv.upload_config.Prepare)
  ))
_sym_db.RegisterMessage(Prepare)

UploadBlock = _reflection.GeneratedProtocolMessageType('UploadBlock', (_message.Message,), dict(
  DESCRIPTOR = _UPLOADBLOCK,
  __module__ = 'srv.upload_config_pb2'
  # @@protoc_insertion_point(class_scope:srv.upload_config.UploadBlock)
  ))
_sym_db.RegisterMessage(UploadBlock)

CheckConfiguration = _reflection.GeneratedProtocolMessageType('CheckConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _CHECKCONFIGURATION,
  __module__ = 'srv.upload_config_pb2'
  # @@protoc_insertion_point(class_scope:srv.upload_config.CheckConfiguration)
  ))
_sym_db.RegisterMessage(CheckConfiguration)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGURATION,
  __module__ = 'srv.upload_config_pb2'
  # @@protoc_insertion_point(class_scope:srv.upload_config.Configuration)
  ))
_sym_db.RegisterMessage(Configuration)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'srv.upload_config_pb2'
  # @@protoc_insertion_point(class_scope:srv.upload_config.File)
  ))
_sym_db.RegisterMessage(File)


# @@protoc_insertion_point(module_scope)
