# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ntag/auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ntag/auth.proto',
  package='ntag.auth',
  syntax='proto2',
  serialized_pb=_b('\n\x0fntag/auth.proto\x12\tntag.auth\"2\n\x08\x43learKey\x12\x13\n\x0bkey_on_card\x18\x01 \x02(\r\x12\x11\n\tclear_key\x18\x02 \x02(\x0c')
)




_CLEARKEY = _descriptor.Descriptor(
  name='ClearKey',
  full_name='ntag.auth.ClearKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_on_card', full_name='ntag.auth.ClearKey.key_on_card', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clear_key', full_name='ntag.auth.ClearKey.clear_key', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['ClearKey'] = _CLEARKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearKey = _reflection.GeneratedProtocolMessageType('ClearKey', (_message.Message,), dict(
  DESCRIPTOR = _CLEARKEY,
  __module__ = 'ntag.auth_pb2'
  # @@protoc_insertion_point(class_scope:ntag.auth.ClearKey)
  ))
_sym_db.RegisterMessage(ClearKey)


# @@protoc_insertion_point(module_scope)
