# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ntag/file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ntag/file.proto',
  package='ntag.file',
  syntax='proto2',
  serialized_pb=_b('\n\x0fntag/file.proto\x12\tntag.file*C\n\x04\x46ile\x12\x18\n\x14\x43\x41PABILITY_CONTAINER\x10\x00\x12\x10\n\x0cNDEF_MESSAGE\x10\x01\x12\x0f\n\x0bPROPRIETARY\x10\x02')
)

_FILE = _descriptor.EnumDescriptor(
  name='File',
  full_name='ntag.file.File',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CAPABILITY_CONTAINER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NDEF_MESSAGE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROPRIETARY', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=30,
  serialized_end=97,
)
_sym_db.RegisterEnumDescriptor(_FILE)

File = enum_type_wrapper.EnumTypeWrapper(_FILE)
CAPABILITY_CONTAINER = 0
NDEF_MESSAGE = 1
PROPRIETARY = 2


DESCRIPTOR.enum_types_by_name['File'] = _FILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
