# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qrcode/exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qrcode/exchange.proto',
  package='qrcode.exchange',
  syntax='proto2',
  serialized_pb=_b('\n\x15qrcode/exchange.proto\x12\x0fqrcode.exchange\"/\n\x0bSendCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x02(\x0c\x12\x0f\n\x07timeout\x18\x02 \x02(\r\"\x1d\n\x0cScannerReply\x12\r\n\x05reply\x18\x01 \x02(\x0c')
)




_SENDCOMMAND = _descriptor.Descriptor(
  name='SendCommand',
  full_name='qrcode.exchange.SendCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='qrcode.exchange.SendCommand.command', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='qrcode.exchange.SendCommand.timeout', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=89,
)


_SCANNERREPLY = _descriptor.Descriptor(
  name='ScannerReply',
  full_name='qrcode.exchange.ScannerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='qrcode.exchange.ScannerReply.reply', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['SendCommand'] = _SENDCOMMAND
DESCRIPTOR.message_types_by_name['ScannerReply'] = _SCANNERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendCommand = _reflection.GeneratedProtocolMessageType('SendCommand', (_message.Message,), dict(
  DESCRIPTOR = _SENDCOMMAND,
  __module__ = 'qrcode.exchange_pb2'
  # @@protoc_insertion_point(class_scope:qrcode.exchange.SendCommand)
  ))
_sym_db.RegisterMessage(SendCommand)

ScannerReply = _reflection.GeneratedProtocolMessageType('ScannerReply', (_message.Message,), dict(
  DESCRIPTOR = _SCANNERREPLY,
  __module__ = 'qrcode.exchange_pb2'
  # @@protoc_insertion_point(class_scope:qrcode.exchange.ScannerReply)
  ))
_sym_db.RegisterMessage(ScannerReply)


# @@protoc_insertion_point(module_scope)
