# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/generic/get_version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/generic/get_version.proto',
  package='mifare.generic.get_version',
  syntax='proto2',
  serialized_pb=_b('\n mifare/generic/get_version.proto\x12\x1amifare.generic.get_version\"\x0c\n\nGetVersion\"\"\n\x12ProductVersionInfo\x12\x0c\n\x04info\x18\x01 \x02(\x0c')
)




_GETVERSION = _descriptor.Descriptor(
  name='GetVersion',
  full_name='mifare.generic.get_version.GetVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=76,
)


_PRODUCTVERSIONINFO = _descriptor.Descriptor(
  name='ProductVersionInfo',
  full_name='mifare.generic.get_version.ProductVersionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='mifare.generic.get_version.ProductVersionInfo.info', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['GetVersion'] = _GETVERSION
DESCRIPTOR.message_types_by_name['ProductVersionInfo'] = _PRODUCTVERSIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetVersion = _reflection.GeneratedProtocolMessageType('GetVersion', (_message.Message,), dict(
  DESCRIPTOR = _GETVERSION,
  __module__ = 'mifare.generic.get_version_pb2'
  # @@protoc_insertion_point(class_scope:mifare.generic.get_version.GetVersion)
  ))
_sym_db.RegisterMessage(GetVersion)

ProductVersionInfo = _reflection.GeneratedProtocolMessageType('ProductVersionInfo', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCTVERSIONINFO,
  __module__ = 'mifare.generic.get_version_pb2'
  # @@protoc_insertion_point(class_scope:mifare.generic.get_version.ProductVersionInfo)
  ))
_sym_db.RegisterMessage(ProductVersionInfo)


# @@protoc_insertion_point(module_scope)
