# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/classic/sector/read_sector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.classic.sector import sector_pb2 as mifare_dot_classic_dot_sector_dot_sector__pb2
from mifare.classic import read_pb2 as mifare_dot_classic_dot_read__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/classic/sector/read_sector.proto',
  package='mifare.classic.sector.read',
  syntax='proto2',
  serialized_pb=_b('\n\'mifare/classic/sector/read_sector.proto\x12\x1amifare.classic.sector.read\x1a\"mifare/classic/sector/sector.proto\x1a\x19mifare/classic/read.proto\"g\n\x0bReadSectors\x12\x35\n\x07sectors\x18\x01 \x03(\x0b\x32$.mifare.classic.sector.sector.Sector\x12!\n\x12read_trailer_block\x18\x02 \x01(\x08:\x05\x66\x61lse\"K\n\x0bSectorsData\x12<\n\x0csectors_data\x18\x01 \x03(\x0b\x32&.mifare.classic.sector.read.SectorData\"P\n\nSectorData\x12\x15\n\rsector_number\x18\x01 \x02(\r\x12+\n\x06\x62locks\x18\x02 \x02(\x0b\x32\x1b.mifare.classic.read.Blocks')
  ,
  dependencies=[mifare_dot_classic_dot_sector_dot_sector__pb2.DESCRIPTOR,mifare_dot_classic_dot_read__pb2.DESCRIPTOR,])




_READSECTORS = _descriptor.Descriptor(
  name='ReadSectors',
  full_name='mifare.classic.sector.read.ReadSectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectors', full_name='mifare.classic.sector.read.ReadSectors.sectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_trailer_block', full_name='mifare.classic.sector.read.ReadSectors.read_trailer_block', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=237,
)


_SECTORSDATA = _descriptor.Descriptor(
  name='SectorsData',
  full_name='mifare.classic.sector.read.SectorsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectors_data', full_name='mifare.classic.sector.read.SectorsData.sectors_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=314,
)


_SECTORDATA = _descriptor.Descriptor(
  name='SectorData',
  full_name='mifare.classic.sector.read.SectorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector_number', full_name='mifare.classic.sector.read.SectorData.sector_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='mifare.classic.sector.read.SectorData.blocks', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=396,
)

_READSECTORS.fields_by_name['sectors'].message_type = mifare_dot_classic_dot_sector_dot_sector__pb2._SECTOR
_SECTORSDATA.fields_by_name['sectors_data'].message_type = _SECTORDATA
_SECTORDATA.fields_by_name['blocks'].message_type = mifare_dot_classic_dot_read__pb2._BLOCKS
DESCRIPTOR.message_types_by_name['ReadSectors'] = _READSECTORS
DESCRIPTOR.message_types_by_name['SectorsData'] = _SECTORSDATA
DESCRIPTOR.message_types_by_name['SectorData'] = _SECTORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadSectors = _reflection.GeneratedProtocolMessageType('ReadSectors', (_message.Message,), dict(
  DESCRIPTOR = _READSECTORS,
  __module__ = 'mifare.classic.sector.read_sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.read.ReadSectors)
  ))
_sym_db.RegisterMessage(ReadSectors)

SectorsData = _reflection.GeneratedProtocolMessageType('SectorsData', (_message.Message,), dict(
  DESCRIPTOR = _SECTORSDATA,
  __module__ = 'mifare.classic.sector.read_sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.read.SectorsData)
  ))
_sym_db.RegisterMessage(SectorsData)

SectorData = _reflection.GeneratedProtocolMessageType('SectorData', (_message.Message,), dict(
  DESCRIPTOR = _SECTORDATA,
  __module__ = 'mifare.classic.sector.read_sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.read.SectorData)
  ))
_sym_db.RegisterMessage(SectorData)


# @@protoc_insertion_point(module_scope)
