# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/classic/sector/sector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.classic import auth_pb2 as mifare_dot_classic_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/classic/sector/sector.proto',
  package='mifare.classic.sector.sector',
  syntax='proto2',
  serialized_pb=_b('\n\"mifare/classic/sector/sector.proto\x12\x1cmifare.classic.sector.sector\x1a\x19mifare/classic/auth.proto\"\x85\x01\n\x06Sector\x12\x32\n\tclear_key\x18\x01 \x01(\x0b\x32\x1d.mifare.classic.auth.ClearKeyH\x00\x12.\n\x07sam_key\x18\x02 \x01(\x0b\x32\x1b.mifare.classic.auth.SamKeyH\x00\x42\x17\n\x15\x61uthentication_method')
  ,
  dependencies=[mifare_dot_classic_dot_auth__pb2.DESCRIPTOR,])




_SECTOR = _descriptor.Descriptor(
  name='Sector',
  full_name='mifare.classic.sector.sector.Sector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clear_key', full_name='mifare.classic.sector.sector.Sector.clear_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sam_key', full_name='mifare.classic.sector.sector.Sector.sam_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='authentication_method', full_name='mifare.classic.sector.sector.Sector.authentication_method',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=96,
  serialized_end=229,
)

_SECTOR.fields_by_name['clear_key'].message_type = mifare_dot_classic_dot_auth__pb2._CLEARKEY
_SECTOR.fields_by_name['sam_key'].message_type = mifare_dot_classic_dot_auth__pb2._SAMKEY
_SECTOR.oneofs_by_name['authentication_method'].fields.append(
  _SECTOR.fields_by_name['clear_key'])
_SECTOR.fields_by_name['clear_key'].containing_oneof = _SECTOR.oneofs_by_name['authentication_method']
_SECTOR.oneofs_by_name['authentication_method'].fields.append(
  _SECTOR.fields_by_name['sam_key'])
_SECTOR.fields_by_name['sam_key'].containing_oneof = _SECTOR.oneofs_by_name['authentication_method']
DESCRIPTOR.message_types_by_name['Sector'] = _SECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sector = _reflection.GeneratedProtocolMessageType('Sector', (_message.Message,), dict(
  DESCRIPTOR = _SECTOR,
  __module__ = 'mifare.classic.sector.sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.sector.Sector)
  ))
_sym_db.RegisterMessage(Sector)


# @@protoc_insertion_point(module_scope)
