# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/classic/sector/write_sector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.classic.sector import sector_pb2 as mifare_dot_classic_dot_sector_dot_sector__pb2
from mifare.classic import write_pb2 as mifare_dot_classic_dot_write__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/classic/sector/write_sector.proto',
  package='mifare.classic.sector.write',
  syntax='proto2',
  serialized_pb=_b('\n(mifare/classic/sector/write_sector.proto\x12\x1bmifare.classic.sector.write\x1a\"mifare/classic/sector/sector.proto\x1a\x1amifare/classic/write.proto\"I\n\x0cWriteSectors\x12\x39\n\x07sectors\x18\x01 \x03(\x0b\x32(.mifare.classic.sector.write.WriteSector\"v\n\x0bWriteSector\x12\x34\n\x06sector\x18\x01 \x02(\x0b\x32$.mifare.classic.sector.sector.Sector\x12\x31\n\x06\x62locks\x18\x02 \x02(\x0b\x32!.mifare.classic.write.WriteBlocks')
  ,
  dependencies=[mifare_dot_classic_dot_sector_dot_sector__pb2.DESCRIPTOR,mifare_dot_classic_dot_write__pb2.DESCRIPTOR,])




_WRITESECTORS = _descriptor.Descriptor(
  name='WriteSectors',
  full_name='mifare.classic.sector.write.WriteSectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sectors', full_name='mifare.classic.sector.write.WriteSectors.sectors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=210,
)


_WRITESECTOR = _descriptor.Descriptor(
  name='WriteSector',
  full_name='mifare.classic.sector.write.WriteSector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector', full_name='mifare.classic.sector.write.WriteSector.sector', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='mifare.classic.sector.write.WriteSector.blocks', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=330,
)

_WRITESECTORS.fields_by_name['sectors'].message_type = _WRITESECTOR
_WRITESECTOR.fields_by_name['sector'].message_type = mifare_dot_classic_dot_sector_dot_sector__pb2._SECTOR
_WRITESECTOR.fields_by_name['blocks'].message_type = mifare_dot_classic_dot_write__pb2._WRITEBLOCKS
DESCRIPTOR.message_types_by_name['WriteSectors'] = _WRITESECTORS
DESCRIPTOR.message_types_by_name['WriteSector'] = _WRITESECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WriteSectors = _reflection.GeneratedProtocolMessageType('WriteSectors', (_message.Message,), dict(
  DESCRIPTOR = _WRITESECTORS,
  __module__ = 'mifare.classic.sector.write_sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.write.WriteSectors)
  ))
_sym_db.RegisterMessage(WriteSectors)

WriteSector = _reflection.GeneratedProtocolMessageType('WriteSector', (_message.Message,), dict(
  DESCRIPTOR = _WRITESECTOR,
  __module__ = 'mifare.classic.sector.write_sector_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.sector.write.WriteSector)
  ))
_sym_db.RegisterMessage(WriteSector)


# @@protoc_insertion_point(module_scope)
