# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/av2/key_position.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/av2/key_position.proto',
  package='mifare.av2.key_position',
  syntax='proto2',
  serialized_pb=_b('\n\x1dmifare/av2/key_position.proto\x12\x17mifare.av2.key_position*=\n\x0bKeyPosition\x12\x0e\n\nPOSITION_A\x10\x00\x12\x0e\n\nPOSITION_B\x10\x01\x12\x0e\n\nPOSITION_C\x10\x02')
)

_KEYPOSITION = _descriptor.EnumDescriptor(
  name='KeyPosition',
  full_name='mifare.av2.key_position.KeyPosition',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POSITION_A', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITION_B', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSITION_C', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=58,
  serialized_end=119,
)
_sym_db.RegisterEnumDescriptor(_KEYPOSITION)

KeyPosition = enum_type_wrapper.EnumTypeWrapper(_KEYPOSITION)
POSITION_A = 0
POSITION_B = 1
POSITION_C = 2


DESCRIPTOR.enum_types_by_name['KeyPosition'] = _KEYPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
