# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/av2/unlock.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.av2 import args_pb2 as mifare_dot_av2_dot_args__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/av2/unlock.proto',
  package='mifare.av2.unlock',
  syntax='proto2',
  serialized_pb=_b('\n\x17mifare/av2/unlock.proto\x12\x11mifare.av2.unlock\x1a\x15mifare/av2/args.proto\"M\n\x06Unlock\x12\x36\n\x04\x61rgs\x18\x01 \x02(\x0b\x32(.mifare.av2.args.AuthenticationArguments\x12\x0b\n\x03key\x18\x02 \x01(\x0c')
  ,
  dependencies=[mifare_dot_av2_dot_args__pb2.DESCRIPTOR,])




_UNLOCK = _descriptor.Descriptor(
  name='Unlock',
  full_name='mifare.av2.unlock.Unlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='mifare.av2.unlock.Unlock.args', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='mifare.av2.unlock.Unlock.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=146,
)

_UNLOCK.fields_by_name['args'].message_type = mifare_dot_av2_dot_args__pb2._AUTHENTICATIONARGUMENTS
DESCRIPTOR.message_types_by_name['Unlock'] = _UNLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Unlock = _reflection.GeneratedProtocolMessageType('Unlock', (_message.Message,), dict(
  DESCRIPTOR = _UNLOCK,
  __module__ = 'mifare.av2.unlock_pb2'
  # @@protoc_insertion_point(class_scope:mifare.av2.unlock.Unlock)
  ))
_sym_db.RegisterMessage(Unlock)


# @@protoc_insertion_point(module_scope)
