# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/plus/counter/copy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/plus/counter/copy.proto',
  package='mifare.plus.counter.copy',
  syntax='proto2',
  serialized_pb=_b('\n\x1emifare/plus/counter/copy.proto\x12\x18mifare.plus.counter.copy\"3\n\x0b\x43opyCounter\x12\x11\n\tsrc_block\x18\x01 \x02(\r\x12\x11\n\tdst_block\x18\x02 \x01(\r')
)




_COPYCOUNTER = _descriptor.Descriptor(
  name='CopyCounter',
  full_name='mifare.plus.counter.copy.CopyCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_block', full_name='mifare.plus.counter.copy.CopyCounter.src_block', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_block', full_name='mifare.plus.counter.copy.CopyCounter.dst_block', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['CopyCounter'] = _COPYCOUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CopyCounter = _reflection.GeneratedProtocolMessageType('CopyCounter', (_message.Message,), dict(
  DESCRIPTOR = _COPYCOUNTER,
  __module__ = 'mifare.plus.counter.copy_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.counter.copy.CopyCounter)
  ))
_sym_db.RegisterMessage(CopyCounter)


# @@protoc_insertion_point(module_scope)
