# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/ultralight/counter/get.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.ultralight.counter import number_pb2 as mifare_dot_ultralight_dot_counter_dot_number__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/ultralight/counter/get.proto',
  package='mifare.ultralight.counter.get',
  syntax='proto2',
  serialized_pb=_b('\n#mifare/ultralight/counter/get.proto\x12\x1dmifare.ultralight.counter.get\x1a&mifare/ultralight/counter/number.proto\"U\n\nGetCounter\x12G\n\x0e\x63ounter_number\x18\x01 \x02(\x0e\x32/.mifare.ultralight.counter.number.CounterNumber\"\x1d\n\x0c\x43ounterValue\x12\r\n\x05value\x18\x01 \x02(\r')
  ,
  dependencies=[mifare_dot_ultralight_dot_counter_dot_number__pb2.DESCRIPTOR,])




_GETCOUNTER = _descriptor.Descriptor(
  name='GetCounter',
  full_name='mifare.ultralight.counter.get.GetCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter_number', full_name='mifare.ultralight.counter.get.GetCounter.counter_number', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=195,
)


_COUNTERVALUE = _descriptor.Descriptor(
  name='CounterValue',
  full_name='mifare.ultralight.counter.get.CounterValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mifare.ultralight.counter.get.CounterValue.value', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=226,
)

_GETCOUNTER.fields_by_name['counter_number'].enum_type = mifare_dot_ultralight_dot_counter_dot_number__pb2._COUNTERNUMBER
DESCRIPTOR.message_types_by_name['GetCounter'] = _GETCOUNTER
DESCRIPTOR.message_types_by_name['CounterValue'] = _COUNTERVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCounter = _reflection.GeneratedProtocolMessageType('GetCounter', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTER,
  __module__ = 'mifare.ultralight.counter.get_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.counter.get.GetCounter)
  ))
_sym_db.RegisterMessage(GetCounter)

CounterValue = _reflection.GeneratedProtocolMessageType('CounterValue', (_message.Message,), dict(
  DESCRIPTOR = _COUNTERVALUE,
  __module__ = 'mifare.ultralight.counter.get_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.counter.get.CounterValue)
  ))
_sym_db.RegisterMessage(CounterValue)


# @@protoc_insertion_point(module_scope)
