# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/ultralight/counter/increment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.ultralight.counter import number_pb2 as mifare_dot_ultralight_dot_counter_dot_number__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/ultralight/counter/increment.proto',
  package='mifare.ultralight.counter.increment',
  syntax='proto2',
  serialized_pb=_b('\n)mifare/ultralight/counter/increment.proto\x12#mifare.ultralight.counter.increment\x1a&mifare/ultralight/counter/number.proto\"l\n\x10IncrementCounter\x12G\n\x0e\x63ounter_number\x18\x01 \x02(\x0e\x32/.mifare.ultralight.counter.number.CounterNumber\x12\x0f\n\x07operand\x18\x02 \x02(\r')
  ,
  dependencies=[mifare_dot_ultralight_dot_counter_dot_number__pb2.DESCRIPTOR,])




_INCREMENTCOUNTER = _descriptor.Descriptor(
  name='IncrementCounter',
  full_name='mifare.ultralight.counter.increment.IncrementCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter_number', full_name='mifare.ultralight.counter.increment.IncrementCounter.counter_number', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operand', full_name='mifare.ultralight.counter.increment.IncrementCounter.operand', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=230,
)

_INCREMENTCOUNTER.fields_by_name['counter_number'].enum_type = mifare_dot_ultralight_dot_counter_dot_number__pb2._COUNTERNUMBER
DESCRIPTOR.message_types_by_name['IncrementCounter'] = _INCREMENTCOUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IncrementCounter = _reflection.GeneratedProtocolMessageType('IncrementCounter', (_message.Message,), dict(
  DESCRIPTOR = _INCREMENTCOUNTER,
  __module__ = 'mifare.ultralight.counter.increment_pb2'
  # @@protoc_insertion_point(class_scope:mifare.ultralight.counter.increment.IncrementCounter)
  ))
_sym_db.RegisterMessage(IncrementCounter)


# @@protoc_insertion_point(module_scope)
