# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/ultralight/counter/number.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/ultralight/counter/number.proto',
  package='mifare.ultralight.counter.number',
  syntax='proto2',
  serialized_pb=_b('\n&mifare/ultralight/counter/number.proto\x12 mifare.ultralight.counter.number*1\n\rCounterNumber\x12\t\n\x05\x46IRST\x10\x00\x12\n\n\x06SECOND\x10\x01\x12\t\n\x05THIRD\x10\x02')
)

_COUNTERNUMBER = _descriptor.EnumDescriptor(
  name='CounterNumber',
  full_name='mifare.ultralight.counter.number.CounterNumber',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECOND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THIRD', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=76,
  serialized_end=125,
)
_sym_db.RegisterEnumDescriptor(_COUNTERNUMBER)

CounterNumber = enum_type_wrapper.EnumTypeWrapper(_COUNTERNUMBER)
FIRST = 0
SECOND = 1
THIRD = 2


DESCRIPTOR.enum_types_by_name['CounterNumber'] = _COUNTERNUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
