# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact/card_slot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact/card_slot.proto',
  package='contact.card_slot',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63ontact/card_slot.proto\x12\x11\x63ontact.card_slot*U\n\x08\x43\x61rdSlot\x12\r\n\tMAIN_SLOT\x10\x00\x12\r\n\tSAM2_SLOT\x10\x02\x12\r\n\tSAM3_SLOT\x10\x03\x12\r\n\tSAM4_SLOT\x10\x04\x12\r\n\tSAM5_SLOT\x10\x05')
)

_CARDSLOT = _descriptor.EnumDescriptor(
  name='CardSlot',
  full_name='contact.card_slot.CardSlot',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAIN_SLOT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM2_SLOT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM3_SLOT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM4_SLOT', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM5_SLOT', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=46,
  serialized_end=131,
)
_sym_db.RegisterEnumDescriptor(_CARDSLOT)

CardSlot = enum_type_wrapper.EnumTypeWrapper(_CARDSLOT)
MAIN_SLOT = 0
SAM2_SLOT = 2
SAM3_SLOT = 3
SAM4_SLOT = 4
SAM5_SLOT = 5


DESCRIPTOR.enum_types_by_name['CardSlot'] = _CARDSLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
