# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact/emv_tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact/emv_tag.proto',
  package='contact.emv_tag',
  syntax='proto2',
  serialized_pb=_b('\n\x15\x63ontact/emv_tag.proto\x12\x0f\x63ontact.emv_tag\"\'\n\x06\x45mvTag\x12\x0e\n\x06number\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x0c')
)




_EMVTAG = _descriptor.Descriptor(
  name='EmvTag',
  full_name='contact.emv_tag.EmvTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='contact.emv_tag.EmvTag.number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='contact.emv_tag.EmvTag.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['EmvTag'] = _EMVTAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmvTag = _reflection.GeneratedProtocolMessageType('EmvTag', (_message.Message,), dict(
  DESCRIPTOR = _EMVTAG,
  __module__ = 'contact.emv_tag_pb2'
  # @@protoc_insertion_point(class_scope:contact.emv_tag.EmvTag)
  ))
_sym_db.RegisterMessage(EmvTag)


# @@protoc_insertion_point(module_scope)
