# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact/iso7816_4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contact import card_slot_pb2 as contact_dot_card__slot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact/iso7816_4.proto',
  package='contact.iso7816_4',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63ontact/iso7816_4.proto\x12\x11\x63ontact.iso7816_4\x1a\x17\x63ontact/card_slot.proto\"O\n\x0cTransmitApdu\x12)\n\x04slot\x18\x01 \x02(\x0e\x32\x1b.contact.card_slot.CardSlot\x12\x14\n\x0c\x63ommand_apdu\x18\x02 \x02(\x0c\"-\n\x0cResponseApdu\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x0f\n\x07trailer\x18\x02 \x02(\r')
  ,
  dependencies=[contact_dot_card__slot__pb2.DESCRIPTOR,])




_TRANSMITAPDU = _descriptor.Descriptor(
  name='TransmitApdu',
  full_name='contact.iso7816_4.TransmitApdu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slot', full_name='contact.iso7816_4.TransmitApdu.slot', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command_apdu', full_name='contact.iso7816_4.TransmitApdu.command_apdu', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=150,
)


_RESPONSEAPDU = _descriptor.Descriptor(
  name='ResponseApdu',
  full_name='contact.iso7816_4.ResponseApdu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='contact.iso7816_4.ResponseApdu.body', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trailer', full_name='contact.iso7816_4.ResponseApdu.trailer', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=197,
)

_TRANSMITAPDU.fields_by_name['slot'].enum_type = contact_dot_card__slot__pb2._CARDSLOT
DESCRIPTOR.message_types_by_name['TransmitApdu'] = _TRANSMITAPDU
DESCRIPTOR.message_types_by_name['ResponseApdu'] = _RESPONSEAPDU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransmitApdu = _reflection.GeneratedProtocolMessageType('TransmitApdu', (_message.Message,), dict(
  DESCRIPTOR = _TRANSMITAPDU,
  __module__ = 'contact.iso7816_4_pb2'
  # @@protoc_insertion_point(class_scope:contact.iso7816_4.TransmitApdu)
  ))
_sym_db.RegisterMessage(TransmitApdu)

ResponseApdu = _reflection.GeneratedProtocolMessageType('ResponseApdu', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEAPDU,
  __module__ = 'contact.iso7816_4_pb2'
  # @@protoc_insertion_point(class_scope:contact.iso7816_4.ResponseApdu)
  ))
_sym_db.RegisterMessage(ResponseApdu)


# @@protoc_insertion_point(module_scope)
