# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact/power_on.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contact import card_slot_pb2 as contact_dot_card__slot__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact/power_on.proto',
  package='contact.power_on',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63ontact/power_on.proto\x12\x10\x63ontact.power_on\x1a\x17\x63ontact/card_slot.proto\"8\n\x0bPowerOnCard\x12)\n\x04slot\x18\x01 \x02(\x0e\x32\x1b.contact.card_slot.CardSlot\"\'\n\x0b\x43ontactCard\x12\x18\n\x10historical_bytes\x18\x01 \x02(\x0c')
  ,
  dependencies=[contact_dot_card__slot__pb2.DESCRIPTOR,])




_POWERONCARD = _descriptor.Descriptor(
  name='PowerOnCard',
  full_name='contact.power_on.PowerOnCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='slot', full_name='contact.power_on.PowerOnCard.slot', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=125,
)


_CONTACTCARD = _descriptor.Descriptor(
  name='ContactCard',
  full_name='contact.power_on.ContactCard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='historical_bytes', full_name='contact.power_on.ContactCard.historical_bytes', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=166,
)

_POWERONCARD.fields_by_name['slot'].enum_type = contact_dot_card__slot__pb2._CARDSLOT
DESCRIPTOR.message_types_by_name['PowerOnCard'] = _POWERONCARD
DESCRIPTOR.message_types_by_name['ContactCard'] = _CONTACTCARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerOnCard = _reflection.GeneratedProtocolMessageType('PowerOnCard', (_message.Message,), dict(
  DESCRIPTOR = _POWERONCARD,
  __module__ = 'contact.power_on_pb2'
  # @@protoc_insertion_point(class_scope:contact.power_on.PowerOnCard)
  ))
_sym_db.RegisterMessage(PowerOnCard)

ContactCard = _reflection.GeneratedProtocolMessageType('ContactCard', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTCARD,
  __module__ = 'contact.power_on_pb2'
  # @@protoc_insertion_point(class_scope:contact.power_on.ContactCard)
  ))
_sym_db.RegisterMessage(ContactCard)


# @@protoc_insertion_point(module_scope)
