# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/buzzer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/buzzer.proto',
  package='misc.buzzer',
  syntax='proto2',
  serialized_pb=_b('\n\x11misc/buzzer.proto\x12\x0bmisc.buzzer\".\n\tMakeSound\x12!\n\x06melody\x18\x01 \x03(\x0b\x32\x11.misc.buzzer.Note\"N\n\x04Note\x12\x14\n\x0c\x66requency_hz\x18\x01 \x02(\r\x12\x13\n\x0b\x64uration_ms\x18\x02 \x02(\r\x12\x1b\n\x13silence_duration_ms\x18\x03 \x01(\r')
)




_MAKESOUND = _descriptor.Descriptor(
  name='MakeSound',
  full_name='misc.buzzer.MakeSound',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='melody', full_name='misc.buzzer.MakeSound.melody', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=80,
)


_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='misc.buzzer.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency_hz', full_name='misc.buzzer.Note.frequency_hz', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration_ms', full_name='misc.buzzer.Note.duration_ms', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='silence_duration_ms', full_name='misc.buzzer.Note.silence_duration_ms', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=160,
)

_MAKESOUND.fields_by_name['melody'].message_type = _NOTE
DESCRIPTOR.message_types_by_name['MakeSound'] = _MAKESOUND
DESCRIPTOR.message_types_by_name['Note'] = _NOTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MakeSound = _reflection.GeneratedProtocolMessageType('MakeSound', (_message.Message,), dict(
  DESCRIPTOR = _MAKESOUND,
  __module__ = 'misc.buzzer_pb2'
  # @@protoc_insertion_point(class_scope:misc.buzzer.MakeSound)
  ))
_sym_db.RegisterMessage(MakeSound)

Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
  DESCRIPTOR = _NOTE,
  __module__ = 'misc.buzzer_pb2'
  # @@protoc_insertion_point(class_scope:misc.buzzer.Note)
  ))
_sym_db.RegisterMessage(Note)


# @@protoc_insertion_point(module_scope)
