# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: misc/event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='misc/event.proto',
  package='misc.event',
  syntax='proto2',
  serialized_pb=_b('\n\x10misc/event.proto\x12\nmisc.event\"a\n\x05\x45vent\x12)\n\nevent_type\x18\x01 \x02(\x0e\x32\x15.misc.event.EventType\x12\x19\n\x11\x65vent_time_offset\x18\x02 \x02(\r\x12\x12\n\nevent_info\x18\x03 \x01(\t*\xe0\x02\n\tEventType\x12\x12\n\x0eWIFI_CONNECTED\x10\x00\x12\x15\n\x11WIFI_DISCONNECTED\x10\x01\x12\x1a\n\x16IP_ADDRESS_IS_OBTAINED\x10\x02\x12\x1a\n\x16\x43ONNECTION_ESTABLISHED\x10\x03\x12#\n\x1f\x43ONNECTION_CLOSED_BY_CONTROLLER\x10\x04\x12\x1f\n\x1b\x43ONNECTION_CLOSED_BY_READER\x10\x05\x12!\n\x1d\x43ONTROLLER_BECAME_UNREACHABLE\x10\x06\x12\x11\n\rDEVICE_REBOOT\x10\x07\x12\x1d\n\x19SAM_POWERED_ON_BY_COMMAND\x10\x08\x12\x1e\n\x1aSAM_POWERED_OFF_BY_COMMAND\x10\t\x12\x1d\n\x19SAM_POWERED_ON_IMPLICITLY\x10\n\x12\x16\n\x12SAM_EXCHANGE_ERROR\x10\x0b')
)

_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='misc.event.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WIFI_CONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WIFI_DISCONNECTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IP_ADDRESS_IS_OBTAINED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_ESTABLISHED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_CLOSED_BY_CONTROLLER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_CLOSED_BY_READER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROLLER_BECAME_UNREACHABLE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_REBOOT', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_POWERED_ON_BY_COMMAND', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_POWERED_OFF_BY_COMMAND', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_POWERED_ON_IMPLICITLY', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_EXCHANGE_ERROR', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=132,
  serialized_end=484,
)
_sym_db.RegisterEnumDescriptor(_EVENTTYPE)

EventType = enum_type_wrapper.EnumTypeWrapper(_EVENTTYPE)
WIFI_CONNECTED = 0
WIFI_DISCONNECTED = 1
IP_ADDRESS_IS_OBTAINED = 2
CONNECTION_ESTABLISHED = 3
CONNECTION_CLOSED_BY_CONTROLLER = 4
CONNECTION_CLOSED_BY_READER = 5
CONTROLLER_BECAME_UNREACHABLE = 6
DEVICE_REBOOT = 7
SAM_POWERED_ON_BY_COMMAND = 8
SAM_POWERED_OFF_BY_COMMAND = 9
SAM_POWERED_ON_IMPLICITLY = 10
SAM_EXCHANGE_ERROR = 11



_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='misc.event.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_type', full_name='misc.event.Event.event_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_time_offset', full_name='misc.event.Event.event_time_offset', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_info', full_name='misc.event.Event.event_info', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=129,
)

_EVENT.fields_by_name['event_type'].enum_type = _EVENTTYPE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.enum_types_by_name['EventType'] = _EVENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'misc.event_pb2'
  # @@protoc_insertion_point(class_scope:misc.event.Event)
  ))
_sym_db.RegisterMessage(Event)


# @@protoc_insertion_point(module_scope)
