# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: failure.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='failure.proto',
  package='common.failure',
  syntax='proto2',
  serialized_pb=_b('\n\rfailure.proto\x12\x0e\x63ommon.failure\"M\n\x0f\x46\x61ilureResponse\x12$\n\x05\x65rror\x18\x01 \x02(\x0e\x32\x15.common.failure.Error\x12\x14\n\x0c\x65rror_string\x18\x02 \x01(\t*\xe3\x06\n\x05\x45rror\x12\x10\n\x0cGENERAL_FAIL\x10\x01\x12\r\n\tNFC_ERROR\x10\x02\x12\x15\n\x11\x43HECKSUM_MISMATCH\x10\x03\x12\x19\n\x15PAYLOAD_PARSING_ERROR\x10\x04\x12\x15\n\x11TRUNCATED_MESSAGE\x10\x05\x12\x13\n\x0fMESSAGE_TOO_BIG\x10\x06\x12\x15\n\x11UNEXPECTED_HEADER\x10\x07\x12\x16\n\x12UNEXPECTED_COMMAND\x10\x08\x12\x1f\n\x1b\x43LESS_CARDS_COLLISION_ERROR\x10\t\x12\x13\n\x0fTIMEOUT_EXPIRED\x10\n\x12\x16\n\x12PROCESSING_STOPPED\x10\x0b\x12\x17\n\x13\x43ONFIGURATION_ERROR\x10\x0c\x12\x10\n\x0c\x43\x41RD_TIMEOUT\x10\r\x12\x17\n\x13UNSUPPORTED_COMMAND\x10\x0e\x12\x15\n\x11INVALID_PARAMETER\x10\x0f\x12\x1a\n\x16NFC_TRANSMISSION_ERROR\x10\x10\x12\'\n#MIFARE_CARD_NOT_ACKNOWLEDGE_COMMAND\x10\x11\x12\x1b\n\x17\x43\x41NCELLED_BY_CARDHOLDER\x10\x12\x12!\n\x1dSECURITY_FUNCTIONS_RESTRICTED\x10\x13\x12\x1c\n\x18MFP_AUTHENTICATION_ERROR\x10\x14\x12\x16\n\x12ICC_IS_NOT_PRESENT\x10\x15\x12\x14\n\x10ICC_IS_NOT_READY\x10\x16\x12\x0f\n\x0bICC_TIMEOUT\x10\x17\x12\x1a\n\x16\x41\x42SENT_HARDWARE_MODULE\x10\x18\x12$\n SAM_AV2_CONDITIONS_NOT_SATISFIED\x10\x19\x12 \n\x1cSAM_AV2_AUTHENTICATION_ERROR\x10\x1a\x12\x1c\n\x18MFC_AUTHENTICATION_ERROR\x10\x1b\x12\x16\n\x12RETRY_LIMIT_IS_OUT\x10\x1c\x12\x15\n\x11RETRY_TIME_IS_OUT\x10\x1d\x12\x19\n\x15INTELLIREADER_IS_BUSY\x10\x1e\x12 \n\x1c\x41T_LEAST_ONE_ACTION_REQUIRED\x10\x1f\x12\x17\n\x13UNSUPPORTED_FEATURE\x10 \x12\x1a\n\x16\x41\x42SENT_QRCODE_HARDWARE\x10!')
)

_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='common.failure.Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENERAL_FAIL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NFC_ERROR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECKSUM_MISMATCH', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYLOAD_PARSING_ERROR', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRUNCATED_MESSAGE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_TOO_BIG', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNEXPECTED_HEADER', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNEXPECTED_COMMAND', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLESS_CARDS_COLLISION_ERROR', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT_EXPIRED', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESSING_STOPPED', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIGURATION_ERROR', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARD_TIMEOUT', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_COMMAND', index=13, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_PARAMETER', index=14, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NFC_TRANSMISSION_ERROR', index=15, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_CARD_NOT_ACKNOWLEDGE_COMMAND', index=16, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELLED_BY_CARDHOLDER', index=17, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECURITY_FUNCTIONS_RESTRICTED', index=18, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MFP_AUTHENTICATION_ERROR', index=19, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICC_IS_NOT_PRESENT', index=20, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICC_IS_NOT_READY', index=21, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICC_TIMEOUT', index=22, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABSENT_HARDWARE_MODULE', index=23, number=24,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_AV2_CONDITIONS_NOT_SATISFIED', index=24, number=25,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAM_AV2_AUTHENTICATION_ERROR', index=25, number=26,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MFC_AUTHENTICATION_ERROR', index=26, number=27,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETRY_LIMIT_IS_OUT', index=27, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETRY_TIME_IS_OUT', index=28, number=29,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTELLIREADER_IS_BUSY', index=29, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AT_LEAST_ONE_ACTION_REQUIRED', index=30, number=31,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_FEATURE', index=31, number=32,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ABSENT_QRCODE_HARDWARE', index=32, number=33,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=113,
  serialized_end=980,
)
_sym_db.RegisterEnumDescriptor(_ERROR)

Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
GENERAL_FAIL = 1
NFC_ERROR = 2
CHECKSUM_MISMATCH = 3
PAYLOAD_PARSING_ERROR = 4
TRUNCATED_MESSAGE = 5
MESSAGE_TOO_BIG = 6
UNEXPECTED_HEADER = 7
UNEXPECTED_COMMAND = 8
CLESS_CARDS_COLLISION_ERROR = 9
TIMEOUT_EXPIRED = 10
PROCESSING_STOPPED = 11
CONFIGURATION_ERROR = 12
CARD_TIMEOUT = 13
UNSUPPORTED_COMMAND = 14
INVALID_PARAMETER = 15
NFC_TRANSMISSION_ERROR = 16
MIFARE_CARD_NOT_ACKNOWLEDGE_COMMAND = 17
CANCELLED_BY_CARDHOLDER = 18
SECURITY_FUNCTIONS_RESTRICTED = 19
MFP_AUTHENTICATION_ERROR = 20
ICC_IS_NOT_PRESENT = 21
ICC_IS_NOT_READY = 22
ICC_TIMEOUT = 23
ABSENT_HARDWARE_MODULE = 24
SAM_AV2_CONDITIONS_NOT_SATISFIED = 25
SAM_AV2_AUTHENTICATION_ERROR = 26
MFC_AUTHENTICATION_ERROR = 27
RETRY_LIMIT_IS_OUT = 28
RETRY_TIME_IS_OUT = 29
INTELLIREADER_IS_BUSY = 30
AT_LEAST_ONE_ACTION_REQUIRED = 31
UNSUPPORTED_FEATURE = 32
ABSENT_QRCODE_HARDWARE = 33



_FAILURERESPONSE = _descriptor.Descriptor(
  name='FailureResponse',
  full_name='common.failure.FailureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='common.failure.FailureResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_string', full_name='common.failure.FailureResponse.error_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=110,
)

_FAILURERESPONSE.fields_by_name['error'].enum_type = _ERROR
DESCRIPTOR.message_types_by_name['FailureResponse'] = _FAILURERESPONSE
DESCRIPTOR.enum_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FailureResponse = _reflection.GeneratedProtocolMessageType('FailureResponse', (_message.Message,), dict(
  DESCRIPTOR = _FAILURERESPONSE,
  __module__ = 'failure_pb2'
  # @@protoc_insertion_point(class_scope:common.failure.FailureResponse)
  ))
_sym_db.RegisterMessage(FailureResponse)


# @@protoc_insertion_point(module_scope)
