# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notification.proto',
  package='common.notification',
  syntax='proto2',
  serialized_pb=_b('\n\x12notification.proto\x12\x13\x63ommon.notification\"\x90\x01\n\x0cNotification\x12\x36\n\x0blog_message\x18\x01 \x01(\x0b\x32\x1f.common.notification.LogMessageH\x00\x12\x38\n\x0cuser_message\x18\x02 \x01(\x0b\x32 .common.notification.UserMessageH\x00\x42\x0e\n\x0cnotification\"\xc3\x01\n\nLogMessage\x12\x39\n\x05level\x18\x01 \x02(\x0e\x32*.common.notification.LogMessage.Importance\x12\x0b\n\x03msg\x18\x02 \x02(\t\"m\n\nImportance\x12\r\n\tEMERGENCY\x10\x01\x12\t\n\x05\x41LERT\x10\x02\x12\x0c\n\x08\x43RITICAL\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0b\n\x07WARNING\x10\x05\x12\n\n\x06NOTICE\x10\x06\x12\x08\n\x04INFO\x10\x07\x12\t\n\x05\x44\x45\x42UG\x10\x08\"u\n\x0bUserMessage\x12>\n\nmessage_id\x18\x01 \x02(\x0e\x32*.common.notification.UserMessage.MessageId\"&\n\tMessageId\x12\x19\n\x15PRESENT_ONE_CARD_ONLY\x10\x00')
)



_LOGMESSAGE_IMPORTANCE = _descriptor.EnumDescriptor(
  name='Importance',
  full_name='common.notification.LogMessage.Importance',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALERT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRITICAL', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARNING', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOTICE', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=277,
  serialized_end=386,
)
_sym_db.RegisterEnumDescriptor(_LOGMESSAGE_IMPORTANCE)

_USERMESSAGE_MESSAGEID = _descriptor.EnumDescriptor(
  name='MessageId',
  full_name='common.notification.UserMessage.MessageId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRESENT_ONE_CARD_ONLY', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=467,
  serialized_end=505,
)
_sym_db.RegisterEnumDescriptor(_USERMESSAGE_MESSAGEID)


_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='common.notification.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='log_message', full_name='common.notification.Notification.log_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_message', full_name='common.notification.Notification.user_message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='notification', full_name='common.notification.Notification.notification',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=44,
  serialized_end=188,
)


_LOGMESSAGE = _descriptor.Descriptor(
  name='LogMessage',
  full_name='common.notification.LogMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='common.notification.LogMessage.level', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='common.notification.LogMessage.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGMESSAGE_IMPORTANCE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=386,
)


_USERMESSAGE = _descriptor.Descriptor(
  name='UserMessage',
  full_name='common.notification.UserMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='common.notification.UserMessage.message_id', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USERMESSAGE_MESSAGEID,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=505,
)

_NOTIFICATION.fields_by_name['log_message'].message_type = _LOGMESSAGE
_NOTIFICATION.fields_by_name['user_message'].message_type = _USERMESSAGE
_NOTIFICATION.oneofs_by_name['notification'].fields.append(
  _NOTIFICATION.fields_by_name['log_message'])
_NOTIFICATION.fields_by_name['log_message'].containing_oneof = _NOTIFICATION.oneofs_by_name['notification']
_NOTIFICATION.oneofs_by_name['notification'].fields.append(
  _NOTIFICATION.fields_by_name['user_message'])
_NOTIFICATION.fields_by_name['user_message'].containing_oneof = _NOTIFICATION.oneofs_by_name['notification']
_LOGMESSAGE.fields_by_name['level'].enum_type = _LOGMESSAGE_IMPORTANCE
_LOGMESSAGE_IMPORTANCE.containing_type = _LOGMESSAGE
_USERMESSAGE.fields_by_name['message_id'].enum_type = _USERMESSAGE_MESSAGEID
_USERMESSAGE_MESSAGEID.containing_type = _USERMESSAGE
DESCRIPTOR.message_types_by_name['Notification'] = _NOTIFICATION
DESCRIPTOR.message_types_by_name['LogMessage'] = _LOGMESSAGE
DESCRIPTOR.message_types_by_name['UserMessage'] = _USERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATION,
  __module__ = 'notification_pb2'
  # @@protoc_insertion_point(class_scope:common.notification.Notification)
  ))
_sym_db.RegisterMessage(Notification)

LogMessage = _reflection.GeneratedProtocolMessageType('LogMessage', (_message.Message,), dict(
  DESCRIPTOR = _LOGMESSAGE,
  __module__ = 'notification_pb2'
  # @@protoc_insertion_point(class_scope:common.notification.LogMessage)
  ))
_sym_db.RegisterMessage(LogMessage)

UserMessage = _reflection.GeneratedProtocolMessageType('UserMessage', (_message.Message,), dict(
  DESCRIPTOR = _USERMESSAGE,
  __module__ = 'notification_pb2'
  # @@protoc_insertion_point(class_scope:common.notification.UserMessage)
  ))
_sym_db.RegisterMessage(UserMessage)


# @@protoc_insertion_point(module_scope)
