# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: troika/av3/time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='troika/av3/time.proto',
  package='troika.av3.time',
  syntax='proto2',
  serialized_pb=_b('\n\x15troika/av3/time.proto\x12\x0ftroika.av3.time\"4\n\x04Time\x12\x0c\n\x04hour\x18\x01 \x02(\r\x12\x0e\n\x06minute\x18\x02 \x02(\r\x12\x0e\n\x06second\x18\x03 \x02(\r')
)




_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='troika.av3.time.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hour', full_name='troika.av3.time.Time.hour', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minute', full_name='troika.av3.time.Time.minute', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='troika.av3.time.Time.second', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['Time'] = _TIME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), dict(
  DESCRIPTOR = _TIME,
  __module__ = 'troika.av3.time_pb2'
  # @@protoc_insertion_point(class_scope:troika.av3.time.Time)
  ))
_sym_db.RegisterMessage(Time)


# @@protoc_insertion_point(module_scope)
