# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: troika/av3/write_ticket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.classic import auth_pb2 as mifare_dot_classic_dot_auth__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='troika/av3/write_ticket.proto',
  package='troika.av3.write_ticket',
  syntax='proto2',
  serialized_pb=_b('\n\x1dtroika/av3/write_ticket.proto\x12\x17troika.av3.write_ticket\x1a\x19mifare/classic/auth.proto\"j\n\x0bWriteTicket\x12+\n\x06sector\x18\x01 \x02(\x0b\x32\x1b.mifare.classic.auth.SamKey\x12\x15\n\rticket_params\x18\x02 \x02(\x0c\x12\x17\n\x0fvalidate_params\x18\x03 \x02(\x0c\"6\n\x0bWriteResult\x12\x15\n\rsector_bitmap\x18\x01 \x02(\x0c\x12\x10\n\x08write_ok\x18\x02 \x02(\x08')
  ,
  dependencies=[mifare_dot_classic_dot_auth__pb2.DESCRIPTOR,])




_WRITETICKET = _descriptor.Descriptor(
  name='WriteTicket',
  full_name='troika.av3.write_ticket.WriteTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector', full_name='troika.av3.write_ticket.WriteTicket.sector', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ticket_params', full_name='troika.av3.write_ticket.WriteTicket.ticket_params', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validate_params', full_name='troika.av3.write_ticket.WriteTicket.validate_params', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=191,
)


_WRITERESULT = _descriptor.Descriptor(
  name='WriteResult',
  full_name='troika.av3.write_ticket.WriteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector_bitmap', full_name='troika.av3.write_ticket.WriteResult.sector_bitmap', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_ok', full_name='troika.av3.write_ticket.WriteResult.write_ok', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=247,
)

_WRITETICKET.fields_by_name['sector'].message_type = mifare_dot_classic_dot_auth__pb2._SAMKEY
DESCRIPTOR.message_types_by_name['WriteTicket'] = _WRITETICKET
DESCRIPTOR.message_types_by_name['WriteResult'] = _WRITERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WriteTicket = _reflection.GeneratedProtocolMessageType('WriteTicket', (_message.Message,), dict(
  DESCRIPTOR = _WRITETICKET,
  __module__ = 'troika.av3.write_ticket_pb2'
  # @@protoc_insertion_point(class_scope:troika.av3.write_ticket.WriteTicket)
  ))
_sym_db.RegisterMessage(WriteTicket)

WriteResult = _reflection.GeneratedProtocolMessageType('WriteResult', (_message.Message,), dict(
  DESCRIPTOR = _WRITERESULT,
  __module__ = 'troika.av3.write_ticket_pb2'
  # @@protoc_insertion_point(class_scope:troika.av3.write_ticket.WriteResult)
  ))
_sym_db.RegisterMessage(WriteResult)


# @@protoc_insertion_point(module_scope)
