# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/classic/auth.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.av2 import args_pb2 as mifare_dot_av2_dot_args__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/classic/auth.proto',
  package='mifare.classic.auth',
  syntax='proto2',
  serialized_pb=_b('\n\x19mifare/classic/auth.proto\x12\x13mifare.classic.auth\x1a\x15mifare/av2/args.proto\"d\n\x08\x43learKey\x12\x15\n\rsector_number\x18\x01 \x02(\r\x12.\n\x08key_type\x18\x02 \x02(\x0e\x32\x1c.mifare.classic.auth.KeyType\x12\x11\n\tclear_key\x18\x03 \x02(\x0c\"\xb0\x01\n\x06SamKey\x12\x15\n\rsector_number\x18\x01 \x02(\r\x12.\n\x08key_type\x18\x02 \x02(\x0e\x32\x1c.mifare.classic.auth.KeyType\x12:\n\x08\x61v2_args\x18\x03 \x02(\x0b\x32(.mifare.av2.args.AuthenticationArguments\x12#\n\x14need_diversification\x18\x04 \x01(\x08:\x05\x66\x61lse*!\n\x07KeyType\x12\n\n\x06TYPE_A\x10\x00\x12\n\n\x06TYPE_B\x10\x01')
  ,
  dependencies=[mifare_dot_av2_dot_args__pb2.DESCRIPTOR,])

_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='mifare.classic.auth.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_A', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_B', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=354,
  serialized_end=387,
)
_sym_db.RegisterEnumDescriptor(_KEYTYPE)

KeyType = enum_type_wrapper.EnumTypeWrapper(_KEYTYPE)
TYPE_A = 0
TYPE_B = 1



_CLEARKEY = _descriptor.Descriptor(
  name='ClearKey',
  full_name='mifare.classic.auth.ClearKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector_number', full_name='mifare.classic.auth.ClearKey.sector_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_type', full_name='mifare.classic.auth.ClearKey.key_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clear_key', full_name='mifare.classic.auth.ClearKey.clear_key', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=173,
)


_SAMKEY = _descriptor.Descriptor(
  name='SamKey',
  full_name='mifare.classic.auth.SamKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector_number', full_name='mifare.classic.auth.SamKey.sector_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_type', full_name='mifare.classic.auth.SamKey.key_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='av2_args', full_name='mifare.classic.auth.SamKey.av2_args', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_diversification', full_name='mifare.classic.auth.SamKey.need_diversification', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=352,
)

_CLEARKEY.fields_by_name['key_type'].enum_type = _KEYTYPE
_SAMKEY.fields_by_name['key_type'].enum_type = _KEYTYPE
_SAMKEY.fields_by_name['av2_args'].message_type = mifare_dot_av2_dot_args__pb2._AUTHENTICATIONARGUMENTS
DESCRIPTOR.message_types_by_name['ClearKey'] = _CLEARKEY
DESCRIPTOR.message_types_by_name['SamKey'] = _SAMKEY
DESCRIPTOR.enum_types_by_name['KeyType'] = _KEYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClearKey = _reflection.GeneratedProtocolMessageType('ClearKey', (_message.Message,), dict(
  DESCRIPTOR = _CLEARKEY,
  __module__ = 'mifare.classic.auth_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.auth.ClearKey)
  ))
_sym_db.RegisterMessage(ClearKey)

SamKey = _reflection.GeneratedProtocolMessageType('SamKey', (_message.Message,), dict(
  DESCRIPTOR = _SAMKEY,
  __module__ = 'mifare.classic.auth_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.auth.SamKey)
  ))
_sym_db.RegisterMessage(SamKey)


# @@protoc_insertion_point(module_scope)
