# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: touchscreen/widget.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='touchscreen/widget.proto',
  package='touchscreen.widget',
  syntax='proto2',
  serialized_pb=_b('\n\x18touchscreen/widget.proto\x12\x12touchscreen.widget\"\x16\n\x08WidgetId\x12\n\n\x02id\x18\x01 \x02(\r')
)




_WIDGETID = _descriptor.Descriptor(
  name='WidgetId',
  full_name='touchscreen.widget.WidgetId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='touchscreen.widget.WidgetId.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['WidgetId'] = _WIDGETID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WidgetId = _reflection.GeneratedProtocolMessageType('WidgetId', (_message.Message,), dict(
  DESCRIPTOR = _WIDGETID,
  __module__ = 'touchscreen.widget_pb2'
  # @@protoc_insertion_point(class_scope:touchscreen.widget.WidgetId)
  ))
_sym_db.RegisterMessage(WidgetId)


# @@protoc_insertion_point(module_scope)
