# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/plus/bulk.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.plus import auth_pb2 as mifare_dot_plus_dot_auth__pb2
from mifare.plus import read_pb2 as mifare_dot_plus_dot_read__pb2
from mifare.plus import write_pb2 as mifare_dot_plus_dot_write__pb2
from mifare.plus.counter import commit_pb2 as mifare_dot_plus_dot_counter_dot_commit__pb2
from mifare.plus.counter import copy_pb2 as mifare_dot_plus_dot_counter_dot_copy__pb2
from mifare.plus.counter import get_pb2 as mifare_dot_plus_dot_counter_dot_get__pb2
from mifare.plus.counter import modify_pb2 as mifare_dot_plus_dot_counter_dot_modify__pb2
from mifare.plus.counter import set_pb2 as mifare_dot_plus_dot_counter_dot_set__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/plus/bulk.proto',
  package='mifare.plus.bulk',
  syntax='proto2',
  serialized_pb=_b('\n\x16mifare/plus/bulk.proto\x12\x10mifare.plus.bulk\x1a\x16mifare/plus/auth.proto\x1a\x16mifare/plus/read.proto\x1a\x17mifare/plus/write.proto\x1a mifare/plus/counter/commit.proto\x1a\x1emifare/plus/counter/copy.proto\x1a\x1dmifare/plus/counter/get.proto\x1a mifare/plus/counter/modify.proto\x1a\x1dmifare/plus/counter/set.proto\"\xaf\x04\n\x07\x43ommand\x12\x37\n\x11\x61uth_on_clear_key\x18\x01 \x01(\x0b\x32\x1a.mifare.plus.auth.ClearKeyH\x00\x12\x33\n\x0bread_blocks\x18\x02 \x01(\x0b\x32\x1c.mifare.plus.read.ReadBlocksH\x00\x12\x36\n\x0cwrite_blocks\x18\x03 \x01(\x0b\x32\x1e.mifare.plus.write.WriteBlocksH\x00\x12:\n\x0bget_counter\x18\x04 \x01(\x0b\x32#.mifare.plus.counter.get.GetCounterH\x00\x12:\n\x0bset_counter\x18\x05 \x01(\x0b\x32#.mifare.plus.counter.set.SetCounterH\x00\x12\x43\n\x0emodify_counter\x18\x06 \x01(\x0b\x32).mifare.plus.counter.modify.ModifyCounterH\x00\x12=\n\x0c\x63opy_counter\x18\x07 \x01(\x0b\x32%.mifare.plus.counter.copy.CopyCounterH\x00\x12\x43\n\x0e\x63ommit_counter\x18\x08 \x01(\x0b\x32).mifare.plus.counter.commit.CommitCounterH\x00\x12\x33\n\x0f\x61uth_on_sam_key\x18\t \x01(\x0b\x32\x18.mifare.plus.auth.SamKeyH\x00\x42\x08\n\x06MfrCmd\"\x86\x01\n\rCommandResult\x12/\n\x0bread_blocks\x18\x01 \x01(\x0b\x32\x18.mifare.plus.read.BlocksH\x00\x12\x37\n\x0bget_counter\x18\x02 \x01(\x0b\x32 .mifare.plus.counter.get.CounterH\x00\x42\x0b\n\tMfrResult\">\n\rBulkOperation\x12-\n\noperations\x18\x01 \x03(\x0b\x32\x19.mifare.plus.bulk.Command\">\n\nBulkResult\x12\x30\n\x07results\x18\x01 \x03(\x0b\x32\x1f.mifare.plus.bulk.CommandResult')
  ,
  dependencies=[mifare_dot_plus_dot_auth__pb2.DESCRIPTOR,mifare_dot_plus_dot_read__pb2.DESCRIPTOR,mifare_dot_plus_dot_write__pb2.DESCRIPTOR,mifare_dot_plus_dot_counter_dot_commit__pb2.DESCRIPTOR,mifare_dot_plus_dot_counter_dot_copy__pb2.DESCRIPTOR,mifare_dot_plus_dot_counter_dot_get__pb2.DESCRIPTOR,mifare_dot_plus_dot_counter_dot_modify__pb2.DESCRIPTOR,mifare_dot_plus_dot_counter_dot_set__pb2.DESCRIPTOR,])




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='mifare.plus.bulk.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth_on_clear_key', full_name='mifare.plus.bulk.Command.auth_on_clear_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_blocks', full_name='mifare.plus.bulk.Command.read_blocks', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_blocks', full_name='mifare.plus.bulk.Command.write_blocks', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_counter', full_name='mifare.plus.bulk.Command.get_counter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_counter', full_name='mifare.plus.bulk.Command.set_counter', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modify_counter', full_name='mifare.plus.bulk.Command.modify_counter', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='copy_counter', full_name='mifare.plus.bulk.Command.copy_counter', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit_counter', full_name='mifare.plus.bulk.Command.commit_counter', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_on_sam_key', full_name='mifare.plus.bulk.Command.auth_on_sam_key', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MfrCmd', full_name='mifare.plus.bulk.Command.MfrCmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=280,
  serialized_end=839,
)


_COMMANDRESULT = _descriptor.Descriptor(
  name='CommandResult',
  full_name='mifare.plus.bulk.CommandResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_blocks', full_name='mifare.plus.bulk.CommandResult.read_blocks', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='get_counter', full_name='mifare.plus.bulk.CommandResult.get_counter', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MfrResult', full_name='mifare.plus.bulk.CommandResult.MfrResult',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=842,
  serialized_end=976,
)


_BULKOPERATION = _descriptor.Descriptor(
  name='BulkOperation',
  full_name='mifare.plus.bulk.BulkOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operations', full_name='mifare.plus.bulk.BulkOperation.operations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=978,
  serialized_end=1040,
)


_BULKRESULT = _descriptor.Descriptor(
  name='BulkResult',
  full_name='mifare.plus.bulk.BulkResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='mifare.plus.bulk.BulkResult.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1042,
  serialized_end=1104,
)

_COMMAND.fields_by_name['auth_on_clear_key'].message_type = mifare_dot_plus_dot_auth__pb2._CLEARKEY
_COMMAND.fields_by_name['read_blocks'].message_type = mifare_dot_plus_dot_read__pb2._READBLOCKS
_COMMAND.fields_by_name['write_blocks'].message_type = mifare_dot_plus_dot_write__pb2._WRITEBLOCKS
_COMMAND.fields_by_name['get_counter'].message_type = mifare_dot_plus_dot_counter_dot_get__pb2._GETCOUNTER
_COMMAND.fields_by_name['set_counter'].message_type = mifare_dot_plus_dot_counter_dot_set__pb2._SETCOUNTER
_COMMAND.fields_by_name['modify_counter'].message_type = mifare_dot_plus_dot_counter_dot_modify__pb2._MODIFYCOUNTER
_COMMAND.fields_by_name['copy_counter'].message_type = mifare_dot_plus_dot_counter_dot_copy__pb2._COPYCOUNTER
_COMMAND.fields_by_name['commit_counter'].message_type = mifare_dot_plus_dot_counter_dot_commit__pb2._COMMITCOUNTER
_COMMAND.fields_by_name['auth_on_sam_key'].message_type = mifare_dot_plus_dot_auth__pb2._SAMKEY
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_on_clear_key'])
_COMMAND.fields_by_name['auth_on_clear_key'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['read_blocks'])
_COMMAND.fields_by_name['read_blocks'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['write_blocks'])
_COMMAND.fields_by_name['write_blocks'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['get_counter'])
_COMMAND.fields_by_name['get_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['set_counter'])
_COMMAND.fields_by_name['set_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['modify_counter'])
_COMMAND.fields_by_name['modify_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['copy_counter'])
_COMMAND.fields_by_name['copy_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['commit_counter'])
_COMMAND.fields_by_name['commit_counter'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMAND.oneofs_by_name['MfrCmd'].fields.append(
  _COMMAND.fields_by_name['auth_on_sam_key'])
_COMMAND.fields_by_name['auth_on_sam_key'].containing_oneof = _COMMAND.oneofs_by_name['MfrCmd']
_COMMANDRESULT.fields_by_name['read_blocks'].message_type = mifare_dot_plus_dot_read__pb2._BLOCKS
_COMMANDRESULT.fields_by_name['get_counter'].message_type = mifare_dot_plus_dot_counter_dot_get__pb2._COUNTER
_COMMANDRESULT.oneofs_by_name['MfrResult'].fields.append(
  _COMMANDRESULT.fields_by_name['read_blocks'])
_COMMANDRESULT.fields_by_name['read_blocks'].containing_oneof = _COMMANDRESULT.oneofs_by_name['MfrResult']
_COMMANDRESULT.oneofs_by_name['MfrResult'].fields.append(
  _COMMANDRESULT.fields_by_name['get_counter'])
_COMMANDRESULT.fields_by_name['get_counter'].containing_oneof = _COMMANDRESULT.oneofs_by_name['MfrResult']
_BULKOPERATION.fields_by_name['operations'].message_type = _COMMAND
_BULKRESULT.fields_by_name['results'].message_type = _COMMANDRESULT
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['CommandResult'] = _COMMANDRESULT
DESCRIPTOR.message_types_by_name['BulkOperation'] = _BULKOPERATION
DESCRIPTOR.message_types_by_name['BulkResult'] = _BULKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'mifare.plus.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.bulk.Command)
  ))
_sym_db.RegisterMessage(Command)

CommandResult = _reflection.GeneratedProtocolMessageType('CommandResult', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDRESULT,
  __module__ = 'mifare.plus.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.bulk.CommandResult)
  ))
_sym_db.RegisterMessage(CommandResult)

BulkOperation = _reflection.GeneratedProtocolMessageType('BulkOperation', (_message.Message,), dict(
  DESCRIPTOR = _BULKOPERATION,
  __module__ = 'mifare.plus.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.bulk.BulkOperation)
  ))
_sym_db.RegisterMessage(BulkOperation)

BulkResult = _reflection.GeneratedProtocolMessageType('BulkResult', (_message.Message,), dict(
  DESCRIPTOR = _BULKRESULT,
  __module__ = 'mifare.plus.bulk_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.bulk.BulkResult)
  ))
_sym_db.RegisterMessage(BulkResult)


# @@protoc_insertion_point(module_scope)
