# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/plus/key_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mifare.plus import sector_pb2 as mifare_dot_plus_dot_sector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/plus/key_type.proto',
  package='mifare.plus.key_type',
  syntax='proto2',
  serialized_pb=_b('\n\x1amifare/plus/key_type.proto\x12\x14mifare.plus.key_type\x1a\x18mifare/plus/sector.proto\"^\n\tSectorKey\x12\x15\n\rsector_number\x18\x01 \x02(\r\x12:\n\x0fsector_key_type\x18\x02 \x02(\x0e\x32!.mifare.plus.sector.SectorKeyType\"\x85\x01\n\x07KeyType\x12\x37\n\x0bspecial_key\x18\x01 \x01(\x0e\x32 .mifare.plus.key_type.SpecialKeyH\x00\x12\x35\n\nsector_key\x18\x02 \x01(\x0b\x32\x1f.mifare.plus.key_type.SectorKeyH\x00\x42\n\n\x08key_type*\x90\x01\n\nSpecialKey\x12\x13\n\x0fORIGINALITY_KEY\x10\x00\x12\x13\n\x0f\x43\x41RD_MASTER_KEY\x10\x01\x12\x13\n\x0f\x43\x41RD_CONFIG_KEY\x10\x02\x12\x15\n\x11LEVEL2_SWITCH_KEY\x10\x03\x12\x15\n\x11LEVEL3_SWITCH_KEY\x10\x04\x12\x15\n\x11SL1_CARD_AUTH_KEY\x10\x05')
  ,
  dependencies=[mifare_dot_plus_dot_sector__pb2.DESCRIPTOR,])

_SPECIALKEY = _descriptor.EnumDescriptor(
  name='SpecialKey',
  full_name='mifare.plus.key_type.SpecialKey',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORIGINALITY_KEY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARD_MASTER_KEY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CARD_CONFIG_KEY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL2_SWITCH_KEY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEVEL3_SWITCH_KEY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SL1_CARD_AUTH_KEY', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=311,
  serialized_end=455,
)
_sym_db.RegisterEnumDescriptor(_SPECIALKEY)

SpecialKey = enum_type_wrapper.EnumTypeWrapper(_SPECIALKEY)
ORIGINALITY_KEY = 0
CARD_MASTER_KEY = 1
CARD_CONFIG_KEY = 2
LEVEL2_SWITCH_KEY = 3
LEVEL3_SWITCH_KEY = 4
SL1_CARD_AUTH_KEY = 5



_SECTORKEY = _descriptor.Descriptor(
  name='SectorKey',
  full_name='mifare.plus.key_type.SectorKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sector_number', full_name='mifare.plus.key_type.SectorKey.sector_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sector_key_type', full_name='mifare.plus.key_type.SectorKey.sector_key_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=172,
)


_KEYTYPE = _descriptor.Descriptor(
  name='KeyType',
  full_name='mifare.plus.key_type.KeyType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='special_key', full_name='mifare.plus.key_type.KeyType.special_key', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sector_key', full_name='mifare.plus.key_type.KeyType.sector_key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key_type', full_name='mifare.plus.key_type.KeyType.key_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=175,
  serialized_end=308,
)

_SECTORKEY.fields_by_name['sector_key_type'].enum_type = mifare_dot_plus_dot_sector__pb2._SECTORKEYTYPE
_KEYTYPE.fields_by_name['special_key'].enum_type = _SPECIALKEY
_KEYTYPE.fields_by_name['sector_key'].message_type = _SECTORKEY
_KEYTYPE.oneofs_by_name['key_type'].fields.append(
  _KEYTYPE.fields_by_name['special_key'])
_KEYTYPE.fields_by_name['special_key'].containing_oneof = _KEYTYPE.oneofs_by_name['key_type']
_KEYTYPE.oneofs_by_name['key_type'].fields.append(
  _KEYTYPE.fields_by_name['sector_key'])
_KEYTYPE.fields_by_name['sector_key'].containing_oneof = _KEYTYPE.oneofs_by_name['key_type']
DESCRIPTOR.message_types_by_name['SectorKey'] = _SECTORKEY
DESCRIPTOR.message_types_by_name['KeyType'] = _KEYTYPE
DESCRIPTOR.enum_types_by_name['SpecialKey'] = _SPECIALKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SectorKey = _reflection.GeneratedProtocolMessageType('SectorKey', (_message.Message,), dict(
  DESCRIPTOR = _SECTORKEY,
  __module__ = 'mifare.plus.key_type_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.key_type.SectorKey)
  ))
_sym_db.RegisterMessage(SectorKey)

KeyType = _reflection.GeneratedProtocolMessageType('KeyType', (_message.Message,), dict(
  DESCRIPTOR = _KEYTYPE,
  __module__ = 'mifare.plus.key_type_pb2'
  # @@protoc_insertion_point(class_scope:mifare.plus.key_type.KeyType)
  ))
_sym_db.RegisterMessage(KeyType)


# @@protoc_insertion_point(module_scope)
