# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/plus/security_level.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/plus/security_level.proto',
  package='mifare.plus.security_level',
  syntax='proto2',
  serialized_pb=_b('\n mifare/plus/security_level.proto\x12\x1amifare.plus.security_level*3\n\rSecurityLevel\x12\x07\n\x03SL0\x10\x00\x12\x07\n\x03SL1\x10\x01\x12\x07\n\x03SL2\x10\x02\x12\x07\n\x03SL3\x10\x03')
)

_SECURITYLEVEL = _descriptor.EnumDescriptor(
  name='SecurityLevel',
  full_name='mifare.plus.security_level.SecurityLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SL0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SL1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SL2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SL3', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=64,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_SECURITYLEVEL)

SecurityLevel = enum_type_wrapper.EnumTypeWrapper(_SECURITYLEVEL)
SL0 = 0
SL1 = 1
SL2 = 2
SL3 = 3


DESCRIPTOR.enum_types_by_name['SecurityLevel'] = _SECURITYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
