# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/emv_removal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/emv_removal.proto',
  package='contactless.emv_removal',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x63ontactless/emv_removal.proto\x12\x17\x63ontactless.emv_removal\"\x1d\n\nEmvRemoval\x12\x0f\n\x07timeout\x18\x01 \x01(\r')
)




_EMVREMOVAL = _descriptor.Descriptor(
  name='EmvRemoval',
  full_name='contactless.emv_removal.EmvRemoval',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeout', full_name='contactless.emv_removal.EmvRemoval.timeout', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['EmvRemoval'] = _EMVREMOVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmvRemoval = _reflection.GeneratedProtocolMessageType('EmvRemoval', (_message.Message,), dict(
  DESCRIPTOR = _EMVREMOVAL,
  __module__ = 'contactless.emv_removal_pb2'
  # @@protoc_insertion_point(class_scope:contactless.emv_removal.EmvRemoval)
  ))
_sym_db.RegisterMessage(EmvRemoval)


# @@protoc_insertion_point(module_scope)
