# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/iso14443_4a.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/iso14443_4a.proto',
  package='contactless.iso14443_4a',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x63ontactless/iso14443_4a.proto\x12\x17\x63ontactless.iso14443_4a\"\x1a\n\x18RequestForAnswerToSelect\"\x1e\n\x0e\x41nswerToSelect\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')
)




_REQUESTFORANSWERTOSELECT = _descriptor.Descriptor(
  name='RequestForAnswerToSelect',
  full_name='contactless.iso14443_4a.RequestForAnswerToSelect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=84,
)


_ANSWERTOSELECT = _descriptor.Descriptor(
  name='AnswerToSelect',
  full_name='contactless.iso14443_4a.AnswerToSelect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='contactless.iso14443_4a.AnswerToSelect.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['RequestForAnswerToSelect'] = _REQUESTFORANSWERTOSELECT
DESCRIPTOR.message_types_by_name['AnswerToSelect'] = _ANSWERTOSELECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestForAnswerToSelect = _reflection.GeneratedProtocolMessageType('RequestForAnswerToSelect', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTFORANSWERTOSELECT,
  __module__ = 'contactless.iso14443_4a_pb2'
  # @@protoc_insertion_point(class_scope:contactless.iso14443_4a.RequestForAnswerToSelect)
  ))
_sym_db.RegisterMessage(RequestForAnswerToSelect)

AnswerToSelect = _reflection.GeneratedProtocolMessageType('AnswerToSelect', (_message.Message,), dict(
  DESCRIPTOR = _ANSWERTOSELECT,
  __module__ = 'contactless.iso14443_4a_pb2'
  # @@protoc_insertion_point(class_scope:contactless.iso14443_4a.AnswerToSelect)
  ))
_sym_db.RegisterMessage(AnswerToSelect)


# @@protoc_insertion_point(module_scope)
