# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/iso14443_4.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/iso14443_4.proto',
  package='contactless.iso14443_4',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x63ontactless/iso14443_4.proto\x12\x16\x63ontactless.iso14443_4\"\x17\n\x07\x43ommand\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\x18\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c')
)




_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='contactless.iso14443_4.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='contactless.iso14443_4.Command.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=79,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='contactless.iso14443_4.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='contactless.iso14443_4.Response.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'contactless.iso14443_4_pb2'
  # @@protoc_insertion_point(class_scope:contactless.iso14443_4.Command)
  ))
_sym_db.RegisterMessage(Command)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'contactless.iso14443_4_pb2'
  # @@protoc_insertion_point(class_scope:contactless.iso14443_4.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
