# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/rf_field.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/rf_field.proto',
  package='contactless.rf_field',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x63ontactless/rf_field.proto\x12\x14\x63ontactless.rf_field\"\x0f\n\rPowerOffField')
)




_POWEROFFFIELD = _descriptor.Descriptor(
  name='PowerOffField',
  full_name='contactless.rf_field.PowerOffField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['PowerOffField'] = _POWEROFFFIELD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerOffField = _reflection.GeneratedProtocolMessageType('PowerOffField', (_message.Message,), dict(
  DESCRIPTOR = _POWEROFFFIELD,
  __module__ = 'contactless.rf_field_pb2'
  # @@protoc_insertion_point(class_scope:contactless.rf_field.PowerOffField)
  ))
_sym_db.RegisterMessage(PowerOffField)


# @@protoc_insertion_point(module_scope)
