# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/token.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from contactless import token_type_pb2 as contactless_dot_token__type__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/token.proto',
  package='contactless.token',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63ontactless/token.proto\x12\x11\x63ontactless.token\x1a\x1c\x63ontactless/token_type.proto\"y\n\x05Token\x12/\n\x04type\x18\x01 \x02(\x0e\x32!.contactless.token_type.TokenType\x12\n\n\x02id\x18\x02 \x02(\x0c\x12\x18\n\x10\x61nswer_to_select\x18\x03 \x01(\x0c\x12\x0c\n\x04\x61tqa\x18\x04 \x01(\x0c\x12\x0b\n\x03sak\x18\x05 \x01(\x0c')
  ,
  dependencies=[contactless_dot_token__type__pb2.DESCRIPTOR,])




_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='contactless.token.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='contactless.token.Token.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='contactless.token.Token.id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answer_to_select', full_name='contactless.token.Token.answer_to_select', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='atqa', full_name='contactless.token.Token.atqa', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sak', full_name='contactless.token.Token.sak', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=197,
)

_TOKEN.fields_by_name['type'].enum_type = contactless_dot_token__type__pb2._TOKENTYPE
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), dict(
  DESCRIPTOR = _TOKEN,
  __module__ = 'contactless.token_pb2'
  # @@protoc_insertion_point(class_scope:contactless.token.Token)
  ))
_sym_db.RegisterMessage(Token)


# @@protoc_insertion_point(module_scope)
