# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/token_carrier_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/token_carrier_type.proto',
  package='contactless.token_carrier_type',
  syntax='proto2',
  serialized_pb=_b('\n$contactless/token_carrier_type.proto\x12\x1e\x63ontactless.token_carrier_type*\x9f\x01\n\x10TokenCarrierType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0cPLASTIC_CARD\x10\x01\x12\x11\n\rMOBILE_DEVICE\x10\x02\x12\x0e\n\nGOOGLE_PAY\x10\x03\x12\r\n\tAPPLE_PAY\x10\x04\x12\x0f\n\x0bSAMSUNG_PAY\x10\x05\x12\x0b\n\x07MIR_PAY\x10\x06\x12\x0e\n\nHUAWEI_PAY\x10\x07\x12\x0c\n\x08SBER_PAY\x10\x08')
)

_TOKENCARRIERTYPE = _descriptor.EnumDescriptor(
  name='TokenCarrierType',
  full_name='contactless.token_carrier_type.TokenCarrierType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLASTIC_CARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILE_DEVICE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOOGLE_PAY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPLE_PAY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SAMSUNG_PAY', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIR_PAY', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HUAWEI_PAY', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SBER_PAY', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=73,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_TOKENCARRIERTYPE)

TokenCarrierType = enum_type_wrapper.EnumTypeWrapper(_TOKENCARRIERTYPE)
UNKNOWN = 0
PLASTIC_CARD = 1
MOBILE_DEVICE = 2
GOOGLE_PAY = 3
APPLE_PAY = 4
SAMSUNG_PAY = 5
MIR_PAY = 6
HUAWEI_PAY = 7
SBER_PAY = 8


DESCRIPTOR.enum_types_by_name['TokenCarrierType'] = _TOKENCARRIERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
