# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactless/token_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactless/token_type.proto',
  package='contactless.token_type',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x63ontactless/token_type.proto\x12\x16\x63ontactless.token_type*\x95\x03\n\tTokenType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0cISO_14443_4A\x10\x01\x12\x10\n\x0cISO_14443_4B\x10\x02\x12\x15\n\x11MIFARE_CLASSIC_1K\x10\x03\x12\x15\n\x11MIFARE_CLASSIC_2K\x10\x04\x12\x15\n\x11MIFARE_CLASSIC_4K\x10\x05\x12\x17\n\x13MIFARE_CLASSIC_MINI\x10\x06\x12\x18\n\x14MIFARE_PLUS_X_SL2_2K\x10\x07\x12\x18\n\x14MIFARE_PLUS_X_SL2_4K\x10\x08\x12\x14\n\x10MIFARE_UL_OR_ULC\x10\t\x12\x1b\n\x17SMART_MX_WITH_MIFARE_1K\x10\n\x12\x1b\n\x17SMART_MX_WITH_MIFARE_4K\x10\x0b\x12\x0e\n\nTAG_N_PLAY\x10\x0c\x12\x0e\n\nSTM_SRI512\x10\r\x12\x14\n\x10GENERIC_ISO15693\x10\x0e\x12\r\n\tICODE_SLI\x10\x0f\x12\x0e\n\nICODE_SLIX\x10\x10\x12\x0f\n\x0bICODE_SLIX2\x10\x11\x12\x0f\n\x0b\x41SK_CTS512B\x10\x12')
)

_TOKENTYPE = _descriptor.EnumDescriptor(
  name='TokenType',
  full_name='contactless.token_type.TokenType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISO_14443_4A', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISO_14443_4B', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_CLASSIC_1K', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_CLASSIC_2K', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_CLASSIC_4K', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_CLASSIC_MINI', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_PLUS_X_SL2_2K', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_PLUS_X_SL2_4K', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIFARE_UL_OR_ULC', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMART_MX_WITH_MIFARE_1K', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMART_MX_WITH_MIFARE_4K', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAG_N_PLAY', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STM_SRI512', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GENERIC_ISO15693', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICODE_SLI', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICODE_SLIX', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICODE_SLIX2', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASK_CTS512B', index=18, number=18,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=57,
  serialized_end=462,
)
_sym_db.RegisterEnumDescriptor(_TOKENTYPE)

TokenType = enum_type_wrapper.EnumTypeWrapper(_TOKENTYPE)
UNKNOWN = 0
ISO_14443_4A = 1
ISO_14443_4B = 2
MIFARE_CLASSIC_1K = 3
MIFARE_CLASSIC_2K = 4
MIFARE_CLASSIC_4K = 5
MIFARE_CLASSIC_MINI = 6
MIFARE_PLUS_X_SL2_2K = 7
MIFARE_PLUS_X_SL2_4K = 8
MIFARE_UL_OR_ULC = 9
SMART_MX_WITH_MIFARE_1K = 10
SMART_MX_WITH_MIFARE_4K = 11
TAG_N_PLAY = 12
STM_SRI512 = 13
GENERIC_ISO15693 = 14
ICODE_SLI = 15
ICODE_SLIX = 16
ICODE_SLIX2 = 17
ASK_CTS512B = 18


DESCRIPTOR.enum_types_by_name['TokenType'] = _TOKENTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
