# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pinpad/key_bundle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pinpad/key_bundle.proto',
  package='pinpad.key_bundle',
  syntax='proto2',
  serialized_pb=_b('\n\x17pinpad/key_bundle.proto\x12\x11pinpad.key_bundle*\x1b\n\x0fKeyBundleFormat\x12\x08\n\x04TR31\x10\x00')
)

_KEYBUNDLEFORMAT = _descriptor.EnumDescriptor(
  name='KeyBundleFormat',
  full_name='pinpad.key_bundle.KeyBundleFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TR31', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=46,
  serialized_end=73,
)
_sym_db.RegisterEnumDescriptor(_KEYBUNDLEFORMAT)

KeyBundleFormat = enum_type_wrapper.EnumTypeWrapper(_KEYBUNDLEFORMAT)
TR31 = 0


DESCRIPTOR.enum_types_by_name['KeyBundleFormat'] = _KEYBUNDLEFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
