# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pinpad/online_pin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pinpad import key_bundle_pb2 as pinpad_dot_key__bundle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pinpad/online_pin.proto',
  package='pinpad.online_pin',
  syntax='proto2',
  serialized_pb=_b('\n\x17pinpad/online_pin.proto\x12\x11pinpad.online_pin\x1a\x17pinpad/key_bundle.proto\"`\n\x0e\x45nterOnlinePin\x12\x0b\n\x03pan\x18\x01 \x02(\x0c\x12\x41\n\x11\x65ncryption_params\x18\x02 \x02(\x0b\x32&.pinpad.online_pin.PinEncryptionParams\"\xb2\x01\n\x13PinEncryptionParams\x12\x36\n\nkey_format\x18\x01 \x02(\x0e\x32\".pinpad.key_bundle.KeyBundleFormat\x12\x13\n\x0bsession_key\x18\x02 \x02(\x0c\x12N\n\x10pin_block_format\x18\x03 \x01(\x0e\x32!.pinpad.online_pin.PinBlockFormat:\x11ISO_9564_FORMAT_4\"P\n\x0b\x45ntryResult\x12.\n\x06status\x18\x01 \x02(\x0e\x32\x1e.pinpad.online_pin.EntryStatus\x12\x11\n\tpin_block\x18\x02 \x01(\x0c*>\n\x0ePinBlockFormat\x12\x15\n\x11ISO_9564_FORMAT_0\x10\x00\x12\x15\n\x11ISO_9564_FORMAT_4\x10\x04*M\n\x0b\x45ntryStatus\x12\x0f\n\x0bPIN_ENTERED\x10\x00\x12\x16\n\x12PIN_ENTRY_BYPASSED\x10\x01\x12\x15\n\x11PIN_ENTRY_TIMEOUT\x10\x02')
  ,
  dependencies=[pinpad_dot_key__bundle__pb2.DESCRIPTOR,])

_PINBLOCKFORMAT = _descriptor.EnumDescriptor(
  name='PinBlockFormat',
  full_name='pinpad.online_pin.PinBlockFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ISO_9564_FORMAT_0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISO_9564_FORMAT_4', index=1, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=432,
  serialized_end=494,
)
_sym_db.RegisterEnumDescriptor(_PINBLOCKFORMAT)

PinBlockFormat = enum_type_wrapper.EnumTypeWrapper(_PINBLOCKFORMAT)
_ENTRYSTATUS = _descriptor.EnumDescriptor(
  name='EntryStatus',
  full_name='pinpad.online_pin.EntryStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PIN_ENTERED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIN_ENTRY_BYPASSED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PIN_ENTRY_TIMEOUT', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=496,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_ENTRYSTATUS)

EntryStatus = enum_type_wrapper.EnumTypeWrapper(_ENTRYSTATUS)
ISO_9564_FORMAT_0 = 0
ISO_9564_FORMAT_4 = 4
PIN_ENTERED = 0
PIN_ENTRY_BYPASSED = 1
PIN_ENTRY_TIMEOUT = 2



_ENTERONLINEPIN = _descriptor.Descriptor(
  name='EnterOnlinePin',
  full_name='pinpad.online_pin.EnterOnlinePin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pan', full_name='pinpad.online_pin.EnterOnlinePin.pan', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encryption_params', full_name='pinpad.online_pin.EnterOnlinePin.encryption_params', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=167,
)


_PINENCRYPTIONPARAMS = _descriptor.Descriptor(
  name='PinEncryptionParams',
  full_name='pinpad.online_pin.PinEncryptionParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_format', full_name='pinpad.online_pin.PinEncryptionParams.key_format', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_key', full_name='pinpad.online_pin.PinEncryptionParams.session_key', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin_block_format', full_name='pinpad.online_pin.PinEncryptionParams.pin_block_format', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=348,
)


_ENTRYRESULT = _descriptor.Descriptor(
  name='EntryResult',
  full_name='pinpad.online_pin.EntryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pinpad.online_pin.EntryResult.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pin_block', full_name='pinpad.online_pin.EntryResult.pin_block', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=430,
)

_ENTERONLINEPIN.fields_by_name['encryption_params'].message_type = _PINENCRYPTIONPARAMS
_PINENCRYPTIONPARAMS.fields_by_name['key_format'].enum_type = pinpad_dot_key__bundle__pb2._KEYBUNDLEFORMAT
_PINENCRYPTIONPARAMS.fields_by_name['pin_block_format'].enum_type = _PINBLOCKFORMAT
_ENTRYRESULT.fields_by_name['status'].enum_type = _ENTRYSTATUS
DESCRIPTOR.message_types_by_name['EnterOnlinePin'] = _ENTERONLINEPIN
DESCRIPTOR.message_types_by_name['PinEncryptionParams'] = _PINENCRYPTIONPARAMS
DESCRIPTOR.message_types_by_name['EntryResult'] = _ENTRYRESULT
DESCRIPTOR.enum_types_by_name['PinBlockFormat'] = _PINBLOCKFORMAT
DESCRIPTOR.enum_types_by_name['EntryStatus'] = _ENTRYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnterOnlinePin = _reflection.GeneratedProtocolMessageType('EnterOnlinePin', (_message.Message,), dict(
  DESCRIPTOR = _ENTERONLINEPIN,
  __module__ = 'pinpad.online_pin_pb2'
  # @@protoc_insertion_point(class_scope:pinpad.online_pin.EnterOnlinePin)
  ))
_sym_db.RegisterMessage(EnterOnlinePin)

PinEncryptionParams = _reflection.GeneratedProtocolMessageType('PinEncryptionParams', (_message.Message,), dict(
  DESCRIPTOR = _PINENCRYPTIONPARAMS,
  __module__ = 'pinpad.online_pin_pb2'
  # @@protoc_insertion_point(class_scope:pinpad.online_pin.PinEncryptionParams)
  ))
_sym_db.RegisterMessage(PinEncryptionParams)

EntryResult = _reflection.GeneratedProtocolMessageType('EntryResult', (_message.Message,), dict(
  DESCRIPTOR = _ENTRYRESULT,
  __module__ = 'pinpad.online_pin_pb2'
  # @@protoc_insertion_point(class_scope:pinpad.online_pin.EntryResult)
  ))
_sym_db.RegisterMessage(EntryResult)


# @@protoc_insertion_point(module_scope)
