# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mifare/classic/counter/get.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mifare/classic/counter/get.proto',
  package='mifare.classic.counter.get',
  syntax='proto2',
  serialized_pb=_b('\n mifare/classic/counter/get.proto\x12\x1amifare.classic.counter.get\"\x1f\n\nGetCounter\x12\x11\n\tsrc_block\x18\x01 \x02(\r\"\x18\n\x07\x43ounter\x12\r\n\x05value\x18\x01 \x02(\x05')
)




_GETCOUNTER = _descriptor.Descriptor(
  name='GetCounter',
  full_name='mifare.classic.counter.get.GetCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_block', full_name='mifare.classic.counter.get.GetCounter.src_block', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=95,
)


_COUNTER = _descriptor.Descriptor(
  name='Counter',
  full_name='mifare.classic.counter.get.Counter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='mifare.classic.counter.get.Counter.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['GetCounter'] = _GETCOUNTER
DESCRIPTOR.message_types_by_name['Counter'] = _COUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCounter = _reflection.GeneratedProtocolMessageType('GetCounter', (_message.Message,), dict(
  DESCRIPTOR = _GETCOUNTER,
  __module__ = 'mifare.classic.counter.get_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.counter.get.GetCounter)
  ))
_sym_db.RegisterMessage(GetCounter)

Counter = _reflection.GeneratedProtocolMessageType('Counter', (_message.Message,), dict(
  DESCRIPTOR = _COUNTER,
  __module__ = 'mifare.classic.counter.get_pb2'
  # @@protoc_insertion_point(class_scope:mifare.classic.counter.get.Counter)
  ))
_sym_db.RegisterMessage(Counter)


# @@protoc_insertion_point(module_scope)
